### ISSUE TITLE
Settings not persistent

### ISSUE THREAD

**Issue by matusaurio** [eneshecan/whatsapp-for-linux#100]
**Description**
The settings are not persistent after a restart of the system.

**To Reproduce**
1. Activate _Close to tray_ option.
2. Enable notifications.
2. Reboot.
3. Settings are disabled again.

**Expected behavior**
App settings should be persistent even after a shutdown or reboot of the system.

**Environment**
 - Manjaro Linux 64-bit
 -  Gnome 3.38.4
 - Wayland

**Comment by eneshecan** [comment]
Hi @matusaurio, thanks for reporting! Could you please share your command line outputs when you run the app in terminal before and after restarting system?

**Comment by eneshecan** [comment]
Well, I see that it's still at version 1.1.2 on Manjaro https://gitlab.manjaro.org/packages/community/whatsapp-for-linux. I am not familiar with how frequently the packages are updated there.

**Comment by matusaurio** [comment]
You're absolutely right, sorry I didn't check the version first.
I'll use the AUR version instead of the Manjaro community one and will report if there's any issue.

**Comment by eneshecan** [comment]
No problem at all, glad we found the issue!
