### ISSUE TITLE
Incorrectly shows "Safari (Mac OS) as logged in device

### ISSUE THREAD

**Issue by tygalive** [eneshecan/whatsapp-for-linux#101]
![Screenshot_20210403-184249_WhatsAppBusiness](https://user-images.githubusercontent.com/19529979/113485277-00e20e80-94ad-11eb-9c75-e81b5ed0bee0.jpg)

Application incorrectly shows Safari (Mac Os) as logged in device, and would be nice to actually show as linux.

**Comment by eneshecan** [comment]
Hi @tygalive, please see #23

**Comment by tygalive** [comment]
Ok thanks, also tried to change the code to use a different user agent but gave up as it seems they do not fully support webkit based browsers.
