### ISSUE TITLE
Add a cleanup part to snap

### ISSUE THREAD

**Issue by 3v1n0** [eneshecan/whatsapp-for-linux#107]
I think you can reduce the snap size by removing some packages that are already provided by the extension.

https://github.com/eneshecan/whatsapp-for-linux/blob/92881797c83674f404ffc2471821e900be3c9833/snap/snapcraft.yaml#L30-L34

In case you can use a "cleanup" stanza to remove from the snap the files that are provided by the extension.

See: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html#manually-adding-to-snapcraft-yaml

**Comment by eneshecan** [comment]
I think most of them are not in the gnome-3-28 extension and that's why I added to make media playing work. However, I guess gnome-3-34 extension covers more.

**Comment by 3v1n0** [comment]
I see, well in any case adding a cleanup part you should be able to catch them, without caring if you added too much stuff.

**Comment by eneshecan** [comment]
Implemented with 4c15e79
