### ISSUE TITLE
tray icon transparent

### ISSUE THREAD

**Issue by Itai-Nelken** [eneshecan/whatsapp-for-linux#111]
**Description**
the tray icon is transparent, I can click it to access the menu, but there is no icon.

https://user-images.githubusercontent.com/70802936/116891923-efb92880-ac37-11eb-9d40-0092dfc80a68.mp4

**Environment**
 - Distro: TwisterOS (based on RaspberryPiOS which is based on debian) armhf.
 - Package: compiled from source.
 - Desktop xfce

**Comment by eneshecan** [comment]
Hi @Itai-Nelken. We kind of improved the icon management in here #98 and still working on it, it'll come in next release...

**Comment by Itai-Nelken** [comment]
@eneshecan thanks! Sorry I didn't see the other issue, you can close this one if you want.

**Comment by cesctiger** [comment]
> **Description**
> 
> the tray icon is transparent, I can click it to access the menu, but there is no icon.
> 
> 
> 
> https://user-images.githubusercontent.com/70802936/116891923-efb92880-ac37-11eb-9d40-0092dfc80a68.mp4
> 
> 
> 
> 
> 
> **Environment**
> 
>  - Distro: TwisterOS (based on RaspberryPiOS which is based on debian) armhf.
> 
>  - Package: compiled from source.
> 
>  - Desktop xfce
> 
>
