### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by fvcr** [eneshecan/whatsapp-for-linux#113]
Hello @eneshecan,

To avoid any DMCA copyright restrictions that WhatsApp/Facebook imposes,
what do you think about changing the name the project?

There was a [Whatsapp-Desktop](https://github.com/Enrico204/Whatsapp-Desktop) project that went through this type of embarrassment,
so I'm warning you, don't feel pressured by me, it's just a concern that comes to mind.

Please see it https://github.com/Enrico204/Whatsapp-Desktop/commit/18ba8a4d007e25112aef46e9a05c09456ee39a11:
> Due to the copyright DMCA that WhatsApp/Facebook is sending to all projects that are using "Whatsapp" in their names, and the lack of time to counteract any changes that WhatsApp team is doing in order to make the development of this project hard, I'm abandoning this project.
> 
> You can find the latest code in the history (the commit before this), at least until Facebook asks for the removal.
> 
> I strongly suggest to switch to another IM client...

Regards.

**Comment by eneshecan** [comment]
Hi @fvcr. Thank you for the warning. I am already aware of this and I don't intend to change the project name just for this. Also it's a shame if they close it down but fine by me since it's just a hobby project.

**Comment by fvcr** [comment]
Hi @xeco23,

I saw that you [renamed the application](https://github.com/xeco23/WasIstLos/issues/399).

I've just opened an [ITP](https://bugs.debian.org/1085480) for WasIstLos.
I've sent it to the [Debian NEW packages queue](https://ftp-master.debian.org/new/wasistlos_1.7.0-1.html), now the FTP-Master team will analyze it.
You can track the changes via the [VCS](https://salsa.debian.org/debian/WasIstLos).
Once accepted, the package will be available in the [Debian Package Tracker](https://tracker.debian.org/wasistlos).

Regards!

**Comment by fvcr** [comment]
Hi @xeco23,
WasIstLos is now available in the Debian archive. \o/
