### ISSUE TITLE
High CPU usage when the focus is on the main window

### ISSUE THREAD

**Issue by Midorina** [eneshecan/whatsapp-for-linux#115]
**Description**
When the focus is on the main window of WhatsApp for Linux, the CPU usage of WebKitWebProcess gradually increases, and weird squeak sounds start to come out of my PC. This has never happened with any other application. Thinking it might be my HDD, I unmounted it, but no, it wasn't that.
- There were no incoming messages during my tests
- There were no additional devices that are connected to any ports (like USB)

I tried searching on internet about why WebKitWebProcess might be doing that but couldn't find anything.

I have never experienced this squeak sound before. This is most likely hardware related and caused by the spike in the performance. I recall hearing it from power adapters of some phones, but not from my PC, not in any game, or under any benchmark.

Also, if you listen closely, you can hear my fans going crazy (Switch between 1:22 and end of the video to hear the difference). Although the usage is not that much, the temps are hitting extremely high values in such a short time span.
![image](https://user-images.githubusercontent.com/22325138/118438567-3d7c6900-b6ed-11eb-91bd-756cc565fc0e.png)
Usually my temperatures are around 40 on idle and 85 at max on load. I've just cleaned it up and refreshed the thermal pastes.

Again, this is most likely a webkit issue, however, there should be a workaround to this.

**To Reproduce**
1. Launch Whatsapp for Linux
2. Make sure you're logged in (doesn't happen if you're not logged in)
3. Make sure the focus is on the main window
4. Check the CPU usages (and possibly listen your PC*)

*I'm not sure if this happens in multiple devices, I don't have the chance to test that, but possibly listen your PC closely for potential squeak sounds as well.

**Expected behavior**
No spike in the usage.

**Screenshots**
YouTube video:
[![WhatsApp for Linux Extremely Weird Behavior](http://img.youtube.com/vi/RHVuRD5j4gk/0.jpg)](http://www.youtube.com/watch?v=RHVuRD5j4gk)

**Environment**
 - Distro:Pop!_OS 20.10 x86_64 
 - Package: snap
 - Desktop Environment: Gnome 3.38.3

**Comment by dianariyanto** [comment]
Same thing here..
please fix

Pop!_OS 20.04 LTS
Gnome 3.36.3
x11

**Comment by eneshecan** [comment]
Is it better if you set the new HW Accel option in preferences to `Never`?

**Comment by eneshecan** [comment]
Does this issue still persist?

**Comment by Midorina** [comment]
I'm sorry, I'm unable to test as I no longer use the same distro nor whatsapp-for-linux.
