### ISSUE TITLE
Consider changing the shortcut for hiding the client side decorations

### ISSUE THREAD

**Issue by tom-james-watson** [eneshecan/whatsapp-for-linux#118]
Pressing `alt` currently toggles the hiding of the client side decorations. I often find the app unintentionally CSD-less, presumably having pressed `alt` at some point. To be honest at first I had no idea what was going on and only when looking for relevant issues did I find that there had been a change to add that shortcut.

I think having the shortcut be a plain modifier key is a bad idea as it will lead to lots of unintentional toggling. It should be a modifier key plus another key, for example `alt+m`, in my opinion.

Thanks for the nice software - much appreciated!

**Comment by tom-james-watson** [comment]
I worked out what is likely the main culprit of this. If I have whatsapp-for-linux as the top window on a workspace and switch to that workspace with Ubuntu's default shortcut of `ctrl+alt+[up/down]`, the CSD will be toggled.

This is because once I switch workspace and let go of `ctrl+alt+[up/down]`, the window is now in focus and it detects the `alt` key release.

**Comment by eneshecan** [comment]
Hi @tom-james-watson, thanks for the report. I think the solution for this would be making the shortcut for showing headerbar holding alt instead of releasing. This is what firefox does.

**Comment by tom-james-watson** [comment]
Mm I'm not sure I quite follow that. On Firefox, *pressing* (not holding) alt will reveal the *menu bar*. It doesn't show/hide the client side decorations themselves. I can't think of any other GTK app where the header bar is hideable like this, or at least it's hidden in the settings somewhere. If people find it useful then that's cool, but I think it's just best to choose a shortcut that's not just a modifier key alone.

**Comment by eneshecan** [comment]
Sorry I meant pressing and releasing. In this case, we can detect the modifiers and do nothing if some other modifier is pressed.

**Comment by eneshecan** [comment]
Fixed with d18dcb4

**Comment by tom-james-watson** [comment]
Awesome - thank you :heart:

Keep up the awesome work - it's much appreciated!
