### ISSUE TITLE
Need to log errors instead of std::cerr

### ISSUE THREAD

**Issue by berkeyvx** [eneshecan/whatsapp-for-linux#121]
**Is your feature request related to a problem? Please describe.**
We need to log errors and some events to text file for users who does encounter with some problem like missing icons on tray or setting file is not setup properly. With this approach, with log files we can see where problems are arise and fix them quickly without waiting user responses on issues.I don't think it will increase the application load. 

**Describe the solution you'd like**
We can write a Logging class or use 3rd party logging libraries.

**Comment by eneshecan** [comment]
I think a common approach for this is redirecting std::cerr to system log files e.g. `journalctl` but I don't know how to do that. Needs to be looked up!

**Comment by eneshecan** [comment]
Implemented with 57ae4c9316e43b00674f4d574f3d67c220ee1f11
