### ISSUE TITLE
[Unimportant] Settings icon color

### ISSUE THREAD

**Issue by Moe1369** [eneshecan/whatsapp-for-linux#122]
![Screenshot from 2021-06-22 18-34-54](https://user-images.githubusercontent.com/65728018/122965639-b627b280-d388-11eb-8820-6e74f1d2bc70.png)

Would be cool if the settings button would fit the chosen color scheme. Maybe there are some gnome resources for that.

**Comment by eneshecan** [comment]
Hi, @Moe1369. The icon color depends on your system icon theme. Please try changing it.

**Comment by Moe1369** [comment]
I'm an idiot. Completely forgot I applied an icon theme. My bad.
