### ISSUE TITLE
video can't be viewed and if i try to download, it lags and a white screen appears after I had to restart whatsapp

### ISSUE THREAD

**Issue by Electrifi** [eneshecan/whatsapp-for-linux#124]
**Description**

**To Reproduce**
4. See the error

**Expected behavior**

**Screenshots**

**Environment**
 - Distro [e.g. Ubuntu, Arch Linux]
 - Package [e.g. snap, debian]
 - Desktop Environment or Window Manager [e.g. Gnome, i3wm]

**Comment by eneshecan** [comment]
I couldn't reproduce the problem. Could you please report your environment?
