### ISSUE TITLE
"cgroup v2 is not fully supported yet"

### ISSUE THREAD

**Issue by CleoMenezes** [eneshecan/whatsapp-for-linux#125]
Just can't open the app.

1. sudo snap install whatsapp-for-linux
2. whatsapp-for-linux

**Expected behavior**
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
/snap/whatsapp-for-linux/25/bin/whatsapp-for-linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)

![image](https://user-images.githubusercontent.com/54215258/125187859-a5d45c00-e1ff-11eb-92e1-fa62f805326d.png)

**Environment**
 -  Fedora
 - Snap
 - Gnome 40

**Comment by CamiloMartinezM** [comment]
Having the same issue.

**Comment by pythonInRelay** [comment]
https://bugs.launchpad.net/snapd/+bug/1916745

It's an upstream issue. Nothing to do with this package.

**Comment by eneshecan** [comment]
I will create a new release soon. Maybe we can keep an eye on this since the new snap build might fix it...
