### ISSUE TITLE
Full screen not working

### ISSUE THREAD

**Issue by theo-coder** [eneshecan/whatsapp-for-linux#127]
**Description**
The fullscreen mentionned in features seams not to work .

**To Reproduce**
Just install for snap

**Environment**
 - Archlinux
 - snap
 - XMonad

**Comment by eneshecan** [comment]
Thanks for opening an issue! Which version of the app is installed on your system? Also, we recently changed the shortcut to `Alt+H` instead of just `Alt`

**Comment by eneshecan** [comment]
Ah sorry, mistaken with the headerbar. Needs to be tested.

**Comment by eneshecan** [comment]
I couldn't reproduce the problem on Ubuntu 21.04 with snap...
