### ISSUE TITLE
The program 'WebKitWebProcess' received an X Window System error.

### ISSUE THREAD

**Issue by jmguzmanc** [eneshecan/whatsapp-for-linux#128]
**Description**
After rejected the option to send notifications to the desktop, I now only see a blank window

From CLI I get

```
(WebKitWebProcess:400367): Gdk-ERROR **: 20:19:13.756: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 213 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```
**Screenshots**
![Screenshot from 2021-07-19 20-22-12](https://user-images.githubusercontent.com/1656628/126243881-60a12b5b-f29c-4fce-995f-c65e1bb1e93d.png)

**Environment**
 - Distro Ubuntu 20.04 LTS 
 - Package: snap
     - whatsapp-for-linux               1.2.0                       25     latest/stable    nshecan            -
 - Desktop Environment: Gnome

**Comment by eneshecan** [comment]
Possibly fixed with c898a81
