### ISSUE TITLE
Error when exec application

### ISSUE THREAD

**Issue by peterwilfride** [eneshecan/whatsapp-for-linux#130]
After compiling the application and exec ./whatsapp-for-linux, I have the following error

`Settings: Failed to load ui resource: Invalid byte sequence in conversion input`

I read that have to install `aspell` of my language, so I install `aspell-pt`, but it's still gives the same error. Also tried `make install` and I've already set up all dependencies, nothing worked.
What should I do?

System: Artix-Linux

**Comment by eneshecan** [comment]
What version of the app are you running? Seems like an old version to me.

**Comment by peterwilfride** [comment]
I cloned from here and compiled, following the tutorial. But I also install using yay/aur and test in my Arch Linux and both didn't work.

> What version of the app are you running? Seems like an old version to me.

**Comment by eneshecan** [comment]
There might be a problem with your system. Could you please try to regenerate your locales with this?
>sudo locale-gen

**Comment by pythonInRelay** [comment]
Exact same issue and I've regen'd my locales.

```
(process:71075): Gtk-WARNING **: 13:55:39.469: Locale not supported by C library.
	Using the fallback 'C' locale.

(whatsapp-for-linux:71075): Gtk-WARNING **: 13:55:39.489: Theme parsing error: gtk-dark.css:6342:10: 'height' is not a valid property name
Settings: Failed to load ui resource: Invalid byte sequence in conversion input
```

**Comment by eneshecan** [comment]
@pythonInRelay Thanks! Could you please report your environment information such as your distro, DE/WM, and maybe the gtkmm version?

**Comment by eneshecan** [comment]
Could you guys please debug the application with `gdb ./whatsapp-for-linux` to see where it breaks?

**Comment by pythonInRelay** [comment]
> @pythonInRelay Thanks! Could you please report your environment information such as your distro, DE/WM, and maybe the gtkmm version?

![neofetch](https://i.imgur.com/K4Saeve.png)

https://privatebin.net/?d323b1301691a9c0#6PgppPLNoYemnQVDkyuP4Xa6VAdwQRe82iDjYXKX5PBe

I can see from the above printout using yay that it "failed to set locale". No idea why that is. As I said, I rebuilt my locale like you requested.

After installing with yay
```
➜  ~ whatsapp-for-linux

(process:86260): Gtk-WARNING **: 08:14:03.252: Locale not supported by C library.
	Using the fallback 'C' locale.

(whatsapp-for-linux:86260): Gtk-WARNING **: 08:14:03.269: Theme parsing error: gtk-dark.css:6342:10: 'height' is not a valid property name
Settings: Failed to load ui resource: Invalid byte sequence in conversion input
```

**Comment by pythonInRelay** [comment]
The snap package is broken due to an upstream issue so I am just using plain old AUR to install

**Comment by eneshecan** [comment]
Please, try rebuilding again since I see from the console output, that is an old error message.

**Comment by 0xb1n4ry** [comment]
I'm getting the same issue
I've done both, build the app myself and install from aur, no difference
I have all the dependencies install with the latest version from the arch repo as of the time of writing this issue.

- cmake - ver. 3.21.3
- gtkmm - ver. 2.24.5-4
- gtkmm3 - ver. 3.24.5-2
- webkit2gtk - ver. 2.32.4 ( this as of writing this issue was flagged as out of date with the latest ver. being 2.34.0 )
- libappindicator-gtk3 - ver. 12.10.0.r296

**Comment by pythonInRelay** [comment]
I gave up on using this and just started using the web.whatsapp.com version. It's far more reliable. I am pretty sure this version of Whatsapp doesn't support groups or anything anyway so I don't see the point in using it and I couldn't even get the AUR version to work reliably.

**Comment by eneshecan** [comment]
I think this can be fixed by calling setlocale(LC_ALL, "") at the first line in main.cpp. @pythonInRelay could you please try?

**Comment by adamant-pwn** [comment]
I have the same issue. Running `whatsapp-for-linux` provides
```
<13>Nov  3 17:15:19 whatsapp-for-linux[732152]: 
<13>Nov  3 17:15:19 whatsapp-for-linux[732152]: (process:732151): Gtk-WARNING **: 17:15:19.934: Locale not supported by C library.
<13>Nov  3 17:15:19 whatsapp-for-linux[732152]:         Using the fallback 'C' locale.
<13>Nov  3 17:15:20 whatsapp-for-linux[732152]: Settings: Failed to load ui resource: Invalid byte sequence in conversion input
```
And `locale` provides
```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_DE.UTF-8
LC_CTYPE="en_DE.UTF-8"
LC_NUMERIC="en_DE.UTF-8"
LC_TIME="en_DE.UTF-8"
LC_COLLATE="en_DE.UTF-8"
LC_MONETARY="en_DE.UTF-8"
LC_MESSAGES="en_DE.UTF-8"
LC_PAPER="en_DE.UTF-8"
LC_NAME="en_DE.UTF-8"
LC_ADDRESS="en_DE.UTF-8"
LC_TELEPHONE="en_DE.UTF-8"
LC_MEASUREMENT="en_DE.UTF-8"
LC_IDENTIFICATION="en_DE.UTF-8"
LC_ALL=
```

I also have the `bsdtar: Failed to set default locale` message on build as well. As I understand, `en_DE.UTF-8` locale is somewhat invalid and it is set by my desktop environment (Plasma 5.23.2). I don't want to change something in its regional settings, as I'd like to have English language with German formats. Any workarounds here?

**Comment by eneshecan** [comment]
Please see #154. I am closing this now.
