### ISSUE TITLE
Start minimised

### ISSUE THREAD

**Issue by hmlendea** [eneshecan/whatsapp-for-linux#136]
Hello,

It'd be useful if there was an option to make this app launch minimised by default.

Similar to "Start in Tray", but instead of being in the tray, it should be minimised (allowing for the "Close to Tray" option to be toggled off)

Why?

In GNOME there is no native tray icon support, and thus, enabling the tray options renders the application unusable, as the window becomes inaccessible. And having the app window start by default and covering the whole screen every time i turn on my PC is unpleasing. It should happen in the background.

Alternatively, a "--starminimised" (or similar) CLI argument would also be great.

**Comment by hmlendea** [comment]
Alternatively, make it so that if the app is launched while it's already running but closed to tray, it brings it out of the tray.

This would basically allow the current functionality to work on GNOME and to act as a "Start minimised" option also

**Comment by 3diamond** [comment]
So what is the command to put in to start minimized in the autostartup in ubuntu 21.10?

**Comment by berkeyvx** [comment]
@3diamond if you mark `Autostart` box and `Start in Tray` boxes, it will auto start at boot with minimized.

**Comment by 3diamond** [comment]
Many thanks for your reply. If you are talking about in settings then I don't have these options. or is it in a different place?

**Comment by berkeyvx** [comment]
![Screenshot from 2022-01-09 19-47-09](https://user-images.githubusercontent.com/44481097/148692005-50dce8ce-30ee-41c2-845b-781ade5d080b.png)

It supposed to be in the leftmost button. If you can't see, please upgrade the version you are using.

**Comment by 3diamond** [comment]
Thanks. I did the upgrade and will not start. I'll check in the issues to try to fix that.

**Comment by Sadi58** [comment]
In case the suggest method doesn't work, a workaround might be an autostart  script to launch the app like this:
```
whatsapp-for-linux &
sleep 2
xdotool windowminimize `xdotool getactivewindow`
```
