### ISSUE TITLE
Snap version doesn't use system font

### ISSUE THREAD

**Issue by nicocarbone** [eneshecan/whatsapp-for-linux#138]
This is a small nitpick: under Ubuntu 21.04, installed using snap, the app doesn't use the system font (which in this case is ubuntu font). I think it should, at lest, use it in the window tittle and menus.

**Comment by eneshecan** [comment]
Hi @nicocarbone, thanks for the issue! gtk by default uses the system font. I believe this is a snap issue. Please try searching on the internet.

**Comment by nicocarbone** [comment]
Hi. I searched in internet. 
I use a lot of snap apps on my PC and none of them have this problem (some use to have it in early versions, but all of them eventually fixed it). I agree it may be a problem in the snap packaging though. Can you point me to the snap maintainer of your app?

**Comment by eneshecan** [comment]
Okay then, sorry. I am the maintainer of snap. Will have a look soon.

**Comment by Vistaus** [comment]
I have the same issue with the version from openSUSE OPI, which is not the Snap version. So I'm guessing it's something else.

**Comment by Vistaus** [comment]
I've just compiled the latest code from git master and the issue is also present there.

**Comment by eneshecan** [comment]
Could you please check whether your gtk-3.0 settings are correctly set up for your system? Should be in your .config/gtk-3.0 folder

**Comment by Vistaus** [comment]
Yes, they are. I have no issues in other GTK apps either.

**Comment by eneshecan** [comment]
Is it only the web view or the whole application?

**Comment by Vistaus** [comment]
Only the web view.

**Comment by Vistaus** [comment]
Thanks for looking into it. That's too bad, as the font is quite hard to read, so I would like to have my system font or at least a way to force it as a custom font.

**Comment by eneshecan** [comment]
No problem, can you paste a screenshot here please?

**Comment by Vistaus** [comment]
I only have one conversation going and that's a private conversation, so I don't want to post a screenshot for privacy reasons.

I don't know if it's hard to read because it really is or if it's just my eyes, but to my eyes it's pretty small and a bit vague.

**Comment by eneshecan** [comment]
No problem at all. I tried something with the latest commit, could you please try the master branch?

**Comment by Vistaus** [comment]
Thanks. It's a little sharper now, but still not 100% sharp and also still too small.

I'm using a 24" 2K screen btw, so not hidpi.

**Comment by eneshecan** [comment]
I added one more commit. Can you try that as well?

**Comment by eneshecan** [comment]
Thank you for all the help btw :)

**Comment by Vistaus** [comment]
No problem - glad to help! 🙂

I don't see any new commit.

**Comment by eneshecan** [comment]
Ah, okay. You must have fetched that as well. Thanks!

**Comment by eneshecan** [comment]
I think we can introduce a `Minimum Font Size` in the Preferences Window to set the `webkit_settings_set_minimum_font_size` which should solve this problem.

If you could try this patch and play with it to see that it works before doing that:
[font_patch.txt](https://github.com/eneshecan/whatsapp-for-linux/files/10520825/font_patch.txt)

**Comment by eneshecan** [comment]
Btw, you can also use the zoom feature to solve this...

**Comment by Vistaus** [comment]
I don't see any zoom feature, but I will try the patch.

**Comment by Vistaus** [comment]
I've played with the patch a bit and that gets me good results. Thank you! 🙂

**Comment by eneshecan** [comment]
> I don't see any zoom feature, but I will try the patch.

It's on the top right popover menu with the three dots icon.

**Comment by Vistaus** [comment]
> > I don't see any zoom feature, but I will try the patch.
> 
> It's on the top right popover menu with the three dots icon.

I see it now. Wow, I looked everywhere for it, even in that menu, but somehow I totally looked over it. Guess I need new glasses. 😆

**Comment by eneshecan** [comment]
Is it good enough or shall we introduce this min font size setting?

**Comment by Vistaus** [comment]
I'll unset the patch later to view the difference.

**Comment by eneshecan** [comment]
Btw, I dropped the last two commits because they don't provide any useful solution...

**Comment by Vistaus** [comment]
Cool, thanks! But that's still only a workaround as the issue calls for use of the system font (which I also still agree with).

**Comment by eneshecan** [comment]
Well, WhatsApp web anyways doesn't allow for us to set the font for itself

**Comment by eneshecan** [comment]
Yes, I tried that but some websites just use their own custom font...

**Comment by Vistaus** [comment]
What about attaching a user CSS script? I know it ain't pretty, but that works in web browsers where you can force fonts. Even on WhatsApp Web (tested in Falkon browser with custom user CSS).

In my case it looks like this:

```
html *
{
  font-family: "Atkinson Hyperlegible", sans-serif !important; 
 }

html* { text-decoration-skip-ink: none; }
a { text-decoration: none; border-bottom:1px solid; }
```

But the font name can be left empty so that WA for Linux users can add their own font name.

**Comment by eneshecan** [comment]
Fair enough, thanks! I think that's doable.

**Comment by eneshecan** [comment]
For starters, getting the system font and setting in the WebView with a call of something like `webkit_web_view_run_javascript` would be sufficient. I am not sure how to apply a custom CSS with WebKit though...

**Comment by Vistaus** [comment]
You can insert custom CSS into web pages with JavaScript. I don't know the details, but you can just install a user script manager in your web browser, go to userstyles.org, click on a style and click on ‘Install as userscript’. So you can see how they do it.

**Comment by joomlafun** [comment]
I have seen multiple thread talking or needing a solution that a css stylesheet would solve.
But all the CSS sources for whatsapp for linux are online, can't there just be a local css file that one can edit?
