### ISSUE TITLE
Cannot Run With "en_AU.utf8" Locale

### ISSUE THREAD

**Issue by squid-tree** [eneshecan/whatsapp-for-linux#139]
**Description**
When used with australian locale, running "whatsapp-for-linux" in terminal outputs the following error: 

"(process:1030187): Gtk-WARNING **: 20:09:37.117: Locale not supported by C library.
        Using the fallback 'C' locale.
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
zsh: abort (core dumped)  LC_ALL=en_US.utf8 whatsapp-for-linux"

When enabling the US locale, however, it functions perfectly. 

**To Reproduce**
1. Run "whatsapp-for-linux" in terminal with australian locale

**Expected behavior**
For the gui to launch

**Environment**
 - Distro: Manjaro Linux
 - Package: AUR
 - Desktop Environment or Window Manager: DWM

**Comment by eneshecan** [comment]
Hi @squid-tree. Could you try this solution, please?

**Comment by eneshecan** [comment]
Fixed by d28b625
