### ISSUE TITLE
Embed UI files or have configurable path for them

### ISSUE THREAD

**Issue by bcbnz** [eneshecan/whatsapp-for-linux#14]
Most if not all distributions will require the UI files to be in /usr/share/whatsapp-for-linux/ui or similar, not in /usr/bin. To support this there should be some way of specifying this path at compile time.

Alternatively, look at embedding the UI files as resources in the executable itself. This will be more convenient for distribution but requires a recompile when the UI files change. https://developer.gnome.org/gtk3/stable/ch01s04.html has some examples of how to compile them, https://stackoverflow.com/questions/60517842/generate-then-use-source-file-using-cmake-in-clion has an example of a CMake command for compiling the resources.

**Comment by eneshecan** [comment]
This would be very useful. Thank you.
