### ISSUE TITLE
Raise/Hide the application window by single left mouse click on tray icon

### ISSUE THREAD

**Issue by lucky62** [eneshecan/whatsapp-for-linux#140]
Current behaviour of tray icon is to show the popup menu.
It is the same for left click and right click (double click not detected, behaves as two single clicks).

Wanted behaviour (similar as Telegram Desktop):
Raise/Hide the application window by left single click.
Show popup menu by right single click.

I know that used libappindicator library is quite restrictive (desribed [here](https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators)).
Personally I don't agree with this solution. My opinion is that applications can be very different thus also tray icons should behave differently - according application needs.

So consider to use different library. Probably you can use xapp-status-icon from libxapp library:
https://github.com/linuxmint/xapp/tree/master/libxapp
https://linuxmint-developer-guide.readthedocs.io/en/latest/xapps.html#libxapp

**Comment by eneshecan** [comment]
Hi @lucky62. Thanks for the suggestion, but right/left click are interpreted same in libappindicator as you mentioned. In my opinion, it's not worth the effort to use a different library for something very specific.
