### ISSUE TITLE
please mention about the settings.conf in readme [i want more docs about this]

### ISSUE THREAD

**Issue by alexzanderr** [eneshecan/whatsapp-for-linux#145]
there is a `~/.config/whatsapp-for-linux/settings.conf`

i want to tell whatsapp-for-linux to not ask me everytime it starts to allow desktop notifications. i want desktop notifications automatically

after looking a little bit in the source code i found this:
```cpp
#pragma once

#include <glibmm/keyfile.h>

class Settings
{
    public:
        static Settings& getInstance();

    public:
        Settings(Settings const&) = delete;
        Settings& operator=(Settings const&) = delete;

    public:
        void   setCloseToTray(bool enable);
        bool   getCloseToTray() const;

        void   setAllowPermissions(bool allow);
        bool   getAllowPermissions() const;

		void   setZoomLevel(double zoomLevel);
        double getZoomLevel() const;

		void   setHeaderBar(bool enable);
        bool   getHeaderBar() const;

		void   setStartInTray(bool enable);
        bool   getStartInTray() const;

		void   setAutostart(bool autostart);
        bool   getAutostart();

    private:
        Settings();
        ~Settings();

    private:
        Glib::KeyFile m_keyFile;
};
```
after looking at this header i came up with the conclusion that set allow permissions automatically includes `desktop notifications`

but using my config (settings.conf) it doesnt work
```
[General]
zoom_level=1.4
allow_permissions=true <------------- i tried with this

[Network]
```

my question is: how to i tell whatsapp-for-linux to enable desktop notifications, if its possible?

**Comment by eneshecan** [comment]
That option is saved to the `settings.conf` file automatically once you enable notifications from the application. If that doesn't work, it might mean that the application doesn't quit properly. Manually, what you do is not correct since this key should be under the `Network` category as the following;

```
[General]
zoom_level=1.4

[Network]
allow_permissions=true
```

**Comment by alexzanderr** [comment]
oooh, i will try with this config and tell you the results. thanks for reply.

**Comment by alexzanderr** [comment]
its working. when starting the app, it doesnt ask to enable desktop notifications anymore. thanks.
