### ISSUE TITLE
Only black window with nvidia, wayland and gnome

### ISSUE THREAD

**Issue by supertomi** [eneshecan/whatsapp-for-linux#148]
**Description**
After using nvidia with wayland under gnome, I see only a black window after launching whatsapp-for-linux. The same environment with nvidia, gnome and X11 is perfect fine.

**To Reproduce**
1. start whatsapp-for-linux from the cli under X11, nvidia and gnome works as expected
2. start the same environment and gnome under wayland => black window

**Screenshots**
tomi@home:~> whatsapp-for-linux 
<13>Nov 21 17:48:35 whatsapp-for-linux[18798]: Settings: Die Schlüsselwertedatei hat keinen Schlüssel »allow_permissions« in der Gruppe »Network«, returning default value.
<13>Nov 21 17:48:36 whatsapp-for-linux[18798]: Settings: Die Schlüsselwertedatei hat keinen Schlüssel »close_to_tray« in der Gruppe »General«, returning default value.
<13>Nov 21 17:48:36 whatsapp-for-linux[18798]: Settings: Die Schlüsselwertedatei hat keinen Schlüssel »start_in_tray« in der Gruppe »General«, returning default value.
<13>Nov 21 17:48:36 whatsapp-for-linux[18798]: Settings: Die Schlüsselwertedatei hat keinen Schlüssel »header_bar« in der Gruppe »General«, returning default value.
<13>Nov 21 17:48:36 whatsapp-for-linux[18798]: Settings: Die Schlüsselwertedatei hat keinen Schlüssel »start_in_tray« in der Gruppe »General«, returning default value.
<13>Nov 21 17:48:36 whatsapp-for-linux[18798]: 
<13>Nov 21 17:48:36 whatsapp-for-linux[18798]: (whatsapp-for-linux:18797): Gtk-CRITICAL **: 17:48:36.136: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

**Environment**
 - Distro resent gentoo with gnome-40.4.0, nvidia-drivers-495.44, whatsapp-for-linux-1.3.0
 - different versions of gnome and nvidia-drivers with the same result

Thanks in advance for help!

**Comment by eneshecan** [comment]
Closing this being unreproducible.

**Comment by the-solipsist** [comment]
I'm having the same issue.  The screen is visible for a while, but then goes blank.

Here's the output if I open it in the terminal:

```
sol@spica ~> whatsapp-for-linux 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: ** (whatsapp-for-linux:20958): WARNING **: 14:07:17.531: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: ** (whatsapp-for-linux:20958): WARNING 
**: 14:07:17.531: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: ** (whatsapp-for-linux:20958): WARNING **: 14:07:17.532: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: ** (whatsapp-for-linux:20958): WARNING **: 14:07:17.532: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “min-font-size” in group “web”, returning default value: 0
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “close-to-tray” in group “general”, returning default value: 0
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “start-in-tray” in group “general”, returning default value: 0
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “start-minimized” in group “general”, returning default value: 0
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: SettingMap: Key file does not have group “appearance”, returning default value: 0
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: (whatsapp-for-linux:20958): Gtk-CRITICAL **: 14:07:17.745: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```
