### ISSUE TITLE
Support for voice/video call

### ISSUE THREAD

**Issue by Raj2032** [eneshecan/whatsapp-for-linux#150]
COmpared to the Windows version we can't do a voice/video call unfortunately. I am hoping this can be added in some time?

**Comment by SolidCapo** [comment]
Any idea if this is on the roadmap? :S would be awesome

**Comment by eljejer** [comment]
Yes please, video call wold be awesom!

**Comment by eneshecan** [comment]
Well, this is not possible unless WhatsApp decides to support it on the web version. Sorry...
