### ISSUE TITLE
'Error resolving' message - SOLVED

### ISSUE THREAD

**Issue by stephenaustin** [eneshecan/whatsapp-for-linux#152]
HI
Attempting to run Whatsapp for Linux on Pop OS 21.10. Getting an error message as follows. Have updated system. Thanks. 

`Error resolving “web.whatsapp.com”: Temporary failure in name resolution`

**Comment by eneshecan** [comment]
Could you please check that if you have the `glib-networking` installed on your system?

**Comment by stephenaustin** [comment]
Thank you for your reply. Yes I do have glib-networking installed. I just ran Whatsapp-for-Linux again and it's working fine now.
