### ISSUE TITLE
The tray icon always shows as if a message has arrived

### ISSUE THREAD

**Issue by devZu9** [eneshecan/whatsapp-for-linux#155]
**Description**
The tray icon always shows as if a message has arrived. This can be seen by the tray icon immediately when the application is loaded (being logged in).

**To Reproduce**
1. Launch the application
2. Maybe it's because of the new "BETA" mode enabled
3. Look in the tray

**Expected behavior**
I expected that after reading all the messages, the tray icon would just be green. And when messages arrive, either an unread message counter or a red dot will be displayed on the icon.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/45079090/149488053-50a45b89-16cc-4abe-ae14-607577daba0e.png)

**Environment**
- Kernel: 5.15.12-1-MANJARO x86_64 
- bits: 64 
- compiler: gcc v: 11.1.0
- Desktop: Xfce 4.16.0 
- Distro: Manjaro Linux 
- base: Arch Linux

**Comment by eneshecan** [comment]
Hi @devZu9. Thank you for reporting.

Normally, when a new notification arrives, it stays in your DE's notification area until you destroy by clicking on it etc. which makes the tray icon to stay in the attention state. Could you please check if that is the case for you?

**Comment by devZu9** [comment]
> Hi @devZu9. Thank you for reporting.
> 
> Normally, when a new notification arrives, it stays in your DE's notification area until you destroy by clicking on it etc. which makes the tray icon to stay in the attention state. Could you please check if that is the case for you?

Hello Friend.
I recorded a video and posted it on YouTube. The duration is only 2 minutes. Please take a look to see for yourself how the incorrect display in the tray occurs.[
Video report.](https://www.youtube.com/watch?v=XnZvePzmv3A)

**Comment by devZu9** [comment]
There have been updates to version 1.4.1-1. The problem remained unresolved.

**Comment by eneshecan** [comment]
I understand now. Well, we don't have access to WhatsApp's API and without it, it's impossible to do this without a hacky solution.

However, the red icon should still go away when you dismiss all the system notifications coming from Whatsapp for Linux. Beware that I am not talking about unread messages in WhatsApp.

**Comment by eneshecan** [comment]
IMO, a nice solution would be;
* Change tray icon's status to normal again when the application window is raised which then we interpret as you've read all of the unread messages.

**Comment by berkeyvx** [comment]
I did a quick test to understand the issue. I built the app via CMake to test this issue. I did the following steps. 

1. Closed app to tray
2. Received message(Tray icon changed to attention)
![Screenshot from 2022-02-04 22-30-47](https://user-images.githubusercontent.com/44481097/152591466-bbc1e861-5906-4450-916a-f433d5e6583f.png)
3. Open the application via the tray icon
4. Read message(Tray icon changed to normal) 
![Screenshot from 2022-02-04 22-30-59](https://user-images.githubusercontent.com/44481097/152591490-909efec2-e10b-4c28-b82c-f392ed6b957c.png)

Tray icon is the theme default one. Not the one that ships with the app. I used Ubuntu 21.04 while doing this test. As Enes said, when I dismissed the system notifications coming from WFL, it changed the tray icon. Anyway, it works but I implemented the solution that Enes suggested. Made a PR #167. You can merge if you think this is a good solution.

**Comment by berkeyvx** [comment]
I made another commit. It only changes the tray icon attention setting if the window is not present when received notification. If we are going to assume the user reads all of the unread messages when the window is raised, In my opinion, if there is a window then the user is aware of notifications hence there is no need to change the tray icon.

Let me know what do you think about these changes :).
