### ISSUE TITLE
Can't install whatsapp-for-linux via Yay anymore

### ISSUE THREAD

**Issue by hayyaun** [eneshecan/whatsapp-for-linux#161]
**Description**
<details>
<summary>
The following package is not available from any mirror to download anymore.
</summary>

```
:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 vala-0.54.5-1-x86_64.pkg.tar.zst failed to download
 Total (1/6)                                                        4.0 MiB   297 KiB/s 00:14 [#######################################################] 100%
error: failed retrieving file 'vala-0.54.5-1-x86_64.pkg.tar.zst' from mirrors.gigenet.com : The requested URL returned error: 404
error: failed retrieving file 'vala-0.54.5-1-x86_64.pkg.tar.zst' from mirrors.ft.uam.es : The requested URL returned error: 404
error: failed retrieving file 'vala-0.54.5-1-x86_64.pkg.tar.zst' from mirrors.huaweicloud.com : The requested URL returned error: 404
error: failed retrieving file 'vala-0.54.5-1-x86_64.pkg.tar.zst' from free.nchc.org.tw : The requested URL returned error: 404
error: failed retrieving file 'vala-0.54.5-1-x86_64.pkg.tar.zst' from mirrors.aliyun.com : The requested URL returned error: 404
error: failed retrieving file 'vala-0.54.5-1-x86_64.pkg.tar.zst' from mirror.netcologne.de : The requested URL returned error: 404
error: failed retrieving file 'vala-0.54.5-1-x86_64.pkg.tar.zst' from mirror.clarkson.edu : The requested URL returned error: 404
error: failed retrieving file 'vala-0.54.5-1-x86_64.pkg.tar.zst' from ftp.vectranet.pl : The requested URL returned error: 404
```
</details>

The gnome/vala-0.54.5-1 is not even available on vala repo.
Mirrors are not available anymore.
The below link is not working.

[vala-0.54.5-1](https://archlinux.pkgs.org/rolling/archlinux-extra-aarch64/vala-0.54.5-1-aarch64.pkg.tar.xz.html)

**Environment**
 - Manjaro Linux
 - Yay
 - KDE Genome5

**Comment by eneshecan** [comment]
Hi @hayyaun. Thanks for reporting! Which package are you trying to install? We don't maintain packages other than snap, appimage, deb, and aur.

**Comment by eneshecan** [comment]
I think the project is remove from Manjaro repos: https://repology.org/project/whatsapp-for-linux/history

**Comment by hayyaun** [comment]
> Hi @hayyaun. Thanks for reporting! Which package are you trying to install? We don't maintain packages other than snap, appimage, deb, and aur.

I think Yay also sync AUR packages. What should I do know?

**Comment by eneshecan** [comment]
The strange thing is we don't have a `vala` dependency. Could you please check if you can install anything at all?

**Comment by hayyaun** [comment]
Yes I can install anything but whatsapp-for-linux.
________________________________

**Comment by ishaanbhimwal** [comment]
```
error: failed retrieving file 'vala-0.54.5-1-x86_64.pkg.tar.zst' from mirrors.gigenet.com : The requested URL returned error: 404
```

If you are on manjaro try updating your mirrors and local database. Then try again with yay:

```
sudo pacman-mirrors --fasttrack 5 && sudo pacman -Syyu
yay -S whatsapp-for-linux
```
