### ISSUE TITLE
No tray icon

### ISSUE THREAD

**Issue by illi-homz** [eneshecan/whatsapp-for-linux#164]
![изображение](https://user-images.githubusercontent.com/54039668/152113127-b578b17d-3f07-4709-a9ca-d8ce1d45c732.png)

Tray icon not showing. However, all functions work.
OS: Linux Mint 20.04
install from snap

**Comment by illi-homz** [comment]
And the dark theme is not applied to the header

**Comment by eneshecan** [comment]
Hi @illi-homz. This is related to the snap environment and we already have an open issue for this. Please see #98
