### ISSUE TITLE
Broken GIF Rendering on Ubuntu 20.04 with KDE Plasma (debian package)

### ISSUE THREAD

**Issue by mirenradia** [eneshecan/whatsapp-for-linux#166]
**Description**
GIFs appear garbled (see screenshot below).

**To Reproduce**
1. Open a chat
2. Click the emoji button to the left of the message box
3. Click the GIF button
4. GIF previews appear distorted as in the screenshot below

Alternatively find a GIF in a recent message and try to click on it to preview. They appear similarly distorted

**Expected behavior**
GIFs should appear correctly (i.e. as they would in a web browser or in the mobile app).

**Screenshots**
![whatsapp-for-linux-gif-rendering-bug](https://user-images.githubusercontent.com/32646026/152364759-da586247-2fdf-486c-aa9d-b39b7bddb6dd.gif)

**Environment**
 - Distro: Ubuntu 20.04
 - Package: debian
 - Desktop Environment or Window Manager: KDE Plasma 5.18.7, KWin 5.18.6

**Comment by mirenradia** [comment]
I think this is caused by the use of the `i965` VA-API driver. I added `LIBVA_DRIVER_NAME=i965` to my `/etc/environment` file as this is what makes hardware accelerated video work for me in my web browser (Brave) but if I launch `whatsapp-for-linux` after unsetting this environment variable, GIF rendering seems to work fine.

**Comment by eneshecan** [comment]
Closing this due to being an upstream issue.
