### ISSUE TITLE
Follow the XDG base directory specification

### ISSUE THREAD

**Issue by bcbnz** [eneshecan/whatsapp-for-linux#17]
The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/index.html) says configuration files should be in `$XDG_CONFIG_HOME/whatsapp-for-linux` (defaults to `~/.config/whatsapp-for-linux`. Currently settings.ini is created in the working directory, which is `$HOME` when running through an application chooser.

**Comment by eneshecan** [comment]
Hmmm, I didin't think about this. Thank you.
