### ISSUE TITLE
Notification sound

### ISSUE THREAD

**Issue by Sadi58** [eneshecan/whatsapp-for-linux#173]
Thanks for this really best WhatsApp desktop client for Linux.
I think adding also **an optional audible notification** would be a very useful enhancement - if it's not something that merely doesn't work with my system, which is KDE neon 5.24.

**Comment by eneshecan** [comment]
Sounds good. We need to check if WebKit provides this by default and if so, check whether this is a DE problem or something is missing in our code.

As a reference, this might be a candidate to enable notification sounds: [https://webkitgtk.org/reference/webkit2gtk/2.8.3/WebKitSettings.html#WebKitSettings--enable-webaudio](WebKitSettings Enable Webaudio)

**Comment by Sadi58** [comment]
Oh, I've just noticed that it's an existing feature that can be toggled in _Settings > Notifications > Sounds_!
The fact that it's not working for me might be related with my  WebKitSettings then - I'll have a look at this, thank you.

**Comment by eneshecan** [comment]
I can confirm that sounds don't work. Tried enabling this [WebKitSettings Enable Webaudio](https://webkitgtk.org/reference/webkit2gtk/2.8.3/WebKitSettings.html#WebKitSettings--enable-webaudio) without success...

**Comment by eneshecan** [comment]
I am not sure if websites produce notification sounds themselves or WhatsApp web does this. If the former one is correct, we can use `libcanberra` to notify users via a simple tone.

**Comment by atom7890** [comment]
notification sound not working 

OS: Arch Linux x86_64 
Kernel: 5.16.13-arch1-1 
DE: GNOME 41.4 
WM: Mutter 
WM Theme: Orchis-dark-compact 
Theme: Orchis-dark-compact [GTK2/3] 
Icons: Adwaita [GTK2/3]

**Comment by Vistaus** [comment]
I support this addition. I currently don't get any notification sound on KDE Plasma, but it would be great to have a sound.

**Comment by eneshecan** [comment]
I am currently working on this. One question: Shall we still play the sound when the window is visible and focused?

**Comment by Vistaus** [comment]
> I am currently working on this.

Yeah!!! 🙂

> One question: Shall we still play the sound when the window is visible and focused?

To me it that would be helpful. I regularly leave the window open when I walk away from my PC, so it would be helpful to know when to walk back. 😉

**Comment by eneshecan** [comment]
Please try it out and let me know if it's working as expected.

**Comment by Vistaus** [comment]
I just updated, now waiting for a message to arrive. 😸

**Comment by Vistaus** [comment]
Sorry, still haven't received a message (I did expect one, though, but didn't happen), so I still have to wait.

**Comment by eneshecan** [comment]
Well, I tested by setting up a friend for me. I am pretty sure that it'll work for you too.

I will try to publish a new release(1.6.0) on the weekend btw.
