### ISSUE TITLE
Crash report when i close the app

### ISSUE THREAD

**Issue by NolannB14** [eneshecan/whatsapp-for-linux#176]
**Description**
I'm on fedora 35 and i decided to install whatsapp for linux to get my conversation inside my computer directly. Fedora send me a crash as soon as i closed the app. Any idea ?

**Comment by berkeyvx** [comment]
Is there more detail about the crash? How do you close the app and does Fedora give you detailed information about crashes?

**Comment by eneshecan** [comment]
Please also provide your environment such as distro, DE/WM, package etc.

**Comment by eneshecan** [comment]
Might be the same issue as #186.
