### ISSUE TITLE
Unable to paste things into chat

### ISSUE THREAD

**Issue by Gisbitus** [eneshecan/whatsapp-for-linux#177]
Unable to paste text or pictures into text boxes.
**Environment**
 - Distro: PopOS 21.10
 - Package snap
 - Desktop Environment or Window Manager: Gnome

**Comment by eneshecan** [comment]
I've also encountered this after switching to wayland. Probably a Wayland only issue and needs to be looked into.

**Comment by eneshecan** [comment]
We have this for images #79 and the other issue is tracked here #159. So, I am closing this.
