### ISSUE TITLE
Can't find dependencies

### ISSUE THREAD

**Issue by Rabioli** [eneshecan/whatsapp-for-linux#178]
**Description**
When trying to compile from source I had problems to detect ayatana-appindicator3-0.1 even though it was installed, I don't know if it is an issue with the naming conventions, but I haven't had this issue before with any other compilation, they all detect the libraries.

I got it to work by changing the CMake file to appindicator3-0.1. However, the issues didn't stop there, in the code itself I needed to copy and paste the path of the library because it couldn't find it, even when Make and Cmake could.

It's not a big issue or a big bug, but it arises in some compatibility problems.
**To Reproduce**
Follow build instructions on Void Linux

**Expected behavior**

**Screenshots**
CMAKE

```
~/whatsapp-for-linux ❯❯❯ cmake -DCMAKE_INSTALL_PREFIX=/usr                                                                                                  
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- Checking for module 'gtkmm-3.0'
--   Found gtkmm-3.0, version 3.24.5
-- Checking for module 'webkit2gtk-4.0'
--   Found webkit2gtk-4.0, version 2.34.6
-- Checking for module 'ayatana-appindicator3-0.1'
--   No package 'ayatana-appindicator3-0.1' found
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  CMakeLists.txt:22 (PKG_CHECK_MODULES)

```

MAKE
```
make[2]: *** [CMakeFiles/whatsapp-for-linux.dir/build.make:80: CMakeFiles/whatsapp-for-linux.dir/src/main.cpp.o] Error 1
In file included from ~/whatsapp-for-linux/src/ui/MainWindow.hpp:9,
                 from ~/whatsapp-for-linux/src/ui/MainWindow.cpp:1:
~/whatsapp-for-linux/src/ui/TrayIcon.hpp:3:10: fatal error: libappindicator/app-indicator.h: No such file or directory
    3 | #include <libappindicator/app-indicator.h>

```
**Environment**
 - Distro Void: Linux Musl
 - Package: source code
 - Desktop: Gnome-wayland

**Comment by berkeyvx** [comment]
I am not sure of the source of the problem but could you try to find installed ayatana packages? On my computer, I could do this with

apt list | grep ayatana-appindicator

Your package manager tool might be different than mine. You might need to execute the different commands.

**Comment by Rabioli** [comment]
Yeah I have them installed but by a different name, for my distro it is specifically this package what I needed to compile and I had it installed. The problem is that it is not detected by make (when I removed the ayatana part it would detect it), but once compiling the C source code of your project couldn't detect it, so I had to manually include it by coping the path the library was in.

I think it is a issue related to naming conventions on debian and derivatives that use apt.

https://voidlinux.pkgs.org/current/voidlinux-main-x86_64/libappindicator-devel-12.10.0_3.x86_64.xbps.html - package needed for compiling in void.

**Comment by eneshecan** [comment]
A note; we recently switched from `libappindicator` to `libayatana-appindicators` due to the former one not being maintained anymore. So, you need the latter one to make the app work properly but I am not sure if your distro provides this. Otherwise, you need to build this package from the source.
