### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by musiclover382** [eneshecan/whatsapp-for-linux#180]
I was wondering if it was possible to localize the project. I would be able to contribute to the Italian translation, and I'm sure lots of other people will translate the program in no time.

Thanks!!

**Comment by eneshecan** [comment]
Hi @musiclover382. This is definitely a good idea. I don't know how this is done in GTK but we need to investigate and create a base code for contributors to easily add their translations. Will try to take a look soon!

**Comment by Vistaus** [comment]
If this gets implemented, then I will provide the Dutch translation. 🙂

**Comment by eneshecan** [comment]
@musiclover382 We don't have any plan of switching our build system. Maybe if you could create a PR with meson, I can help to adapt it to cmake.

**Comment by eneshecan** [comment]
Anyone who wants to contribute can find the instructions in the [wiki](https://github.com/eneshecan/whatsapp-for-linux/wiki#translations).

**Comment by musiclover382** [comment]
@eneshecan Tysm for implementing this. I actually forgot about it and later lost the project during a distrohop... I'm happy we can enjoy this feature now 😃️

**Comment by eneshecan** [comment]
### To the ones who pushed their translations;

Thanks a lot for contributing!

Please watch for changes in `po/whatsapp-for-linux.pot` file to update your translations until I find a way to automate this process in a user-friendly manner.

**Comment by Vistaus** [comment]
Automation would be nice, but if you want a easy way for now, you could just announce here that you're about to release a new version. That way, all subscribers to this issue are automatically notified. :-)

**Comment by eneshecan** [comment]
There is a new option in PreferencesWindow called `Prefer Dark Theme`. Please update your translations.

Thanks!

**Comment by eneshecan** [comment]
I set up a POEditor project for the translations here https://poeditor.com/join/project/jMGkxVn3vN. I am still trying to figure out how it works, but the basic functionality for us is there.

Added @bordam and @Vistaus to the project there since I was able to find their emails. Please contact me via nshecan@gmail.com, or write a comment here with your email, or use the link above to get access as admin/contributor.

**Comment by eneshecan** [comment]
If you updated your translations on POEditor, please don't forget to export to GitHub.

**Comment by eneshecan** [comment]
Ah, that works only if you are an admin. I will make all of you Admin there now.

**Comment by Vistaus** [comment]
Ah, thanks!
