### ISSUE TITLE
Icon not respecting system icon theme

### ISSUE THREAD

**Issue by mirenradia** [eneshecan/whatsapp-for-linux#182]
**Description**
Ever since the rerelease of v1.4.2, the application icon in Latte Dock is not respecting the system icon theme. I am using the [Papirus-Dark icon theme](https://git.io/papirus-icon-theme).

**To Reproduce**
1. Since `com.github.eneshecan.WhatsAppForLinux` does not exist in the Papirus icon theme, I have created symbol links to `/usr/share/icons/Papirus/<size>/apps/whatsapp.svg` at `~/.local/share/icons/Papirus-Dark/<size>/apps/com.github.eneshecan.WhatsAppForLinux.svg` where `<size>` is `16x16`, `22x22`, `24x24`, `32x32`, `64x64`, `96x96`, `128x128`. I have done something similar for the tray icon under `~/.local/share/icons/Papirus-Dark/<size>/panel/com.github.eneshecan.WhatsAppForLinux.Tray.svg` and  `~/.local/share/icons/Papirus-Dark/<size>/panel/com.github.eneshecan.WhatsAppForLinux.Tray.Attention.svg` for the smallest 3 sizes and this seems to work fine.
2. Open the app and observe the icon in Latte dock.

**Expected behavior**
The icon should respect the system icon theme assuming that an icon of the form `com.github.eneshecan.WhatsAppForLinux.<ext>` exists for the relevant theme. 

**Environment**
 - Distro: Ubuntu 20.04.4
 - Package: debian
 - Desktop Environment or Window Manager: KDE Plasma 5.18.8

**Comment by eneshecan** [comment]
Hi @mirenradia. The icons for the tray should be installed in your `/usr/share/hicolor/<size>/status/` folders. Also, I updated the release twice since I forgot to rename the tray icons. Could you please check if you have the latest package and the correct path?

**Comment by mirenradia** [comment]
Sorry, I meant the tray icon respects the icon theme but the main application icon in my dock does not.

**Comment by eneshecan** [comment]
Ah, okay. Then, I am not sure what is going wrong there compared to older versions since I only changed the icon name.

**Comment by mirenradia** [comment]
So it turns out Papirus had an icon for the old name (see [here](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2574)) so I tried doing something similar by symbolically linking `/usr/share/icons/Paprius/<size>/apps/com.github.eneshecan.WhatsAppForLinux.svg` to `/usr/share/icons/Paprius/<size>/apps/whatsapp.svg` for all the sizes of the old one and it still seems to not work :slightly_frowning_face: For now, I'm going to use 1.4.1.

**Comment by drakkar1969** [comment]
A PR has been merged to add the new icons in Papirus: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/pull/3099

**Comment by drakkar1969** [comment]
The Papirus PR does not seem to solve the issue for the application icon in the application switcher, dock or GNOME overview:

![Untitled](https://user-images.githubusercontent.com/18715287/168485161-8dda8782-bb8e-4e2c-8dd4-2130e150a250.png)

The icon is fine in the GNOME application list, and tray icons work correctly.

**Comment by eneshecan** [comment]
@drakkar1969 Please see #185 for that.
