### ISSUE TITLE
Validation via md5sums fails

### ISSUE THREAD

**Issue by marcodellomo** [eneshecan/whatsapp-for-linux#184]
**Description**
Validation via md5sums fails when trying to update package via pamac GUI.

**To Reproduce**
1. When pamac icon notifies available updates, click on it and open pamac GUI;
2. Whait few seconds till all the available updates of intalled packages are found;
3. Click on 'Apply' button, on the bottom of the page, than enter the password to log in as super user; click on the 'Apply' button on the top of the page reporting the packages to be built;
4. Package update is started; wait till it stops  reporting "unable to update package" and showing the log file.
5. Scroll down the log file and read that the problem is validation via md5sums failure.

**Expected behavior**
Update via pamac GUI should work with no problems.

**Environment**
 - Distro: Manjaro
 - Package: AUR
 - Desktop Environment or Window Manager: XFCE 4.16

**Comment by eneshecan** [comment]
Hi @marcodellomo, thanks for reporting. This is a `pamac` [issue](https://gitlab.manjaro.org/applications/pamac/-/issues/535), as I mentioned here as well: https://aur.archlinux.org/packages/whatsapp-for-linux.

**Comment by marcodellomo** [comment]
I just solved the problem by eliminating the old AUR build files for this package then updating again.
This probably was a problem dated a few days ago and was already solved, but my computer still had old corrupted build files from an previous update attempt, so when i tried to update it didn't download the new ones solving the problem.

I just thank you for your attention, maybe this could be useful for other users experiencing the same issue.
