### ISSUE TITLE
Incorrect display of the icon of the running application.

### ISSUE THREAD

**Issue by rus-99-pk** [eneshecan/whatsapp-for-linux#185]
**Description**
I downloaded the latest version of the app from snap. Found a small problem - when you open the application, the icon disappears when the application is open from below.
 
I tried editing the Icon line in "whatsapp-for-linux.desktop" along these paths:
 
/var/lib/snapd/snap/whatsapp-for-linux/32/share/applications
/var/lib/snapd/snap/whatsapp-for-linux/31/meta/gui
/var/lib/snapd/snap/whatsapp-for-linux/31/share/applications
 
But due to access problems I could not edit it, maybe during the installation it will be possible to prescribe the correct paths.

**To Reproduce**
Open Application.

**Expected behavior**
Must be WhatsApp icon.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/93255418/161396322-fa899600-5124-46e6-89ef-dcf48c24cc5f.png)

**Environment**
Distro: Fedora 35
package: snap
Desktop Environment or Window Manager: Gnome

**Comment by drakkar1969** [comment]
I'm on Arch Linux/GNOME, installing with the AUR package (https://aur.archlinux.org/packages/whatsapp-for-linux) and having the same issue.
In looking glass, the wmclass shows up as `whatsapp-for-linux`, and the issue can be solved by adding the following line to the .desktop file:

```
StartupWMClass=whatsapp-for-linux
```

**Comment by bkmo** [comment]
> I'm on Arch Linux/GNOME, installing with the AUR package (https://aur.archlinux.org/packages/whatsapp-for-linux) and having the same issue. In looking glass, the wmclass shows up as `whatsapp-for-linux`, and the issue can be solved by adding the following line to the .desktop file:
> 
> ```
> StartupWMClass=whatsapp-for-linux
> ```

Worked for me on Arch too....thanks

**Comment by eneshecan** [comment]
Let me see if it makes sense introduce that option into our desktop file then.
