### ISSUE TITLE
Error when closing application.

### ISSUE THREAD

**Issue by rus-99-pk** [eneshecan/whatsapp-for-linux#186]
**Description**
When closing the application, an error appears (doesn't always work):

--- Running report_uReport ---
Error: No segments found in coredump './coredump'
("report_uReport" exited with exit code 1)

**To Reproduce**
1. Launch the Application
2. Click on 'Autostart'
3. Close the Application
4. Launch the Application
5. See the error

**Environment**
 - Distro: Fedora 35
 - Package: snap
 - Desktop Environment or Window Manager: Gnome

**Comment by eneshecan** [comment]
Hi @rus-99-pk, thanks for reporting. I think I've found the culprit. App fails to create an autostart desktop entry if there is no `autostart` folder in the config directory which is the case for snaps. Needs to be fixed.
