### ISSUE TITLE
App doesn't open

### ISSUE THREAD

**Issue by Gisbitus** [eneshecan/whatsapp-for-linux#190]
<13>Apr  5 16:15:32 whatsapp-for-linux[35219]: Gtk-Message: 16:15:32.055: Failed to load module "appmenu-gtk-module"
<13>Apr  5 16:15:32 whatsapp-for-linux[35219]: 
<13>Apr  5 16:15:32 whatsapp-for-linux[35219]: (whatsapp-for-linux:35147): dbind-WARNING **: 16:15:32.059: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-z7TzVHVf9K: No such file or directory
<13>Apr  5 16:15:32 whatsapp-for-linux[35219]: 
<13>Apr  5 16:15:32 whatsapp-for-linux[35219]: ** (whatsapp-for-linux:35147): WARNING **: 16:15:32.124: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied
<13>Apr  5 16:15:32 whatsapp-for-linux[35219]: 
<13>Apr  5 16:15:32 whatsapp-for-linux[35219]: ** (whatsapp-for-linux:35147): WARNING **: 16:15:32.124: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
<13>Apr  5 16:15:32 whatsapp-for-linux[35219]: 
<13>Apr  5 16:15:32 whatsapp-for-linux[35219]: ** (whatsapp-for-linux:35147): ERROR **: 16:15:32.126: Unable to fork a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)
Trace/breakpoint trap (core dumped)

**Comment by slarrain** [comment]
Same here.

```sh
<13>Apr  5 17:44:13 whatsapp-for-linux[32523]:
<13>Apr  5 17:44:13 whatsapp-for-linux[32523]: ** (whatsapp-for-linux:32445): WARNING **: 17:44:13.699: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied
<13>Apr  5 17:44:13 whatsapp-for-linux[32523]:
<13>Apr  5 17:44:13 whatsapp-for-linux[32523]: ** (whatsapp-for-linux:32445): WARNING **: 17:44:13.699: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
<13>Apr  5 17:44:13 whatsapp-for-linux[32523]:
<13>Apr  5 17:44:13 whatsapp-for-linux[32523]: ** (whatsapp-for-linux:32445): ERROR **: 17:44:13.702: Unable to fork a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)
```

**Comment by eneshecan** [comment]
Please see #189
