### ISSUE TITLE
Messages not received, stays on one tick

### ISSUE THREAD

**Issue by richard-muvirimi** [eneshecan/whatsapp-for-linux#193]
**Description**
Messages are not delivered and stay on one tick. Chrome browser works normally on WhatsApp web website. Even had the mobile phone open with the same chat and would synchronize the message, but still show one tick on both devices.

**To Reproduce**
1. Send message whatsapp-for-linux
2. Send messages on mobile or WhatsApp website
3. Message sent on whatsapp-for-linux stays on one tick
4. Message sent on mobile and Whatsapp messages changes to two ticks and the recipient acknowledges receiving the message

**Expected behavior**
The message should be sent and received as on the web version

**Screenshots**
![image](https://user-images.githubusercontent.com/19529979/162204360-02c97178-d308-4aec-bf24-b31fee69ff38.png)

**Environment**
 - Distro: Manjaro 
 - Package: Pamac
 - Desktop Environment or Window Manager: Gnome 41.3

This has been going on for some time but managed to isolate the issue to messages I had sent through the app. My guess is this started after the update where you could run Whatsapp on multiple devices

Thank you for the great app.

**Comment by JaapStruyk** [comment]
Experiencing the same thing, sending with whatsapp-for-linux, message only gets one tick but does appear on my phone's whatsapp also with one tick but is not send.
Strange thing is that in my case this only happens with one contact, all the others (so far) no problems.

**Comment by eneshecan** [comment]
I don't think this is a problem on our side.
