### ISSUE TITLE
database error occurred on your browser. Please restart your computer and relink your device

### ISSUE THREAD

**Issue by hendranata** [eneshecan/whatsapp-for-linux#195]
**Description**
we face strange issue sometime we got error: database error occurred on your browser. Please restart your computer and relink your device

**To Reproduce**
this suddenly logout my whatsapp.. cant predict when..but after couple days always show that error

**Expected behavior**
no error like that..

**Screenshots**
https://ibb.co/GRZ6H06

**Environment**
 - ubuntu 18 LTS
 - deb
 - Desktop Environment or Window Manager [e.g. Gnome, i3wm]

**Comment by sergey-chechaev** [comment]
> **Description** we face strange issue sometime we got error: database error occurred on your browser. Please restart your computer and relink your device
> 
> **To Reproduce** this suddenly logout my whatsapp.. cant predict when..but after couple days always show that error
> 
> **Expected behavior** no error like that..
> 
> **Screenshots** https://ibb.co/GRZ6H06
> 
> **Environment**
> 
> * ubuntu 18 LTS
> * deb
> * Desktop Environment or Window Manager [e.g. Gnome, i3wm]

It seems that WhatsApp has bug after update. Send bug report to WhatsApp email: [support@whatsapp.com](mailto:support@whatsapp.com) or in mobile Application "Settings" -> "Help" -> "Contact Us"

**Comment by sergey-chechaev** [comment]
https://www.reddit.com/r/whatsapp/comments/ttkkuv/whatsapp_web_doesnt_work_on_my_ipad_with_ios_12/

**Comment by hendranata** [comment]
I am running whatsapp-for-linux using sudo seems working normal


Sent from Yahoo Mail for iPhone


On Thursday, April 14, 2022, 6:12 PM, Sergey ***@***.***> wrote:




https://www.reddit.com/r/whatsapp/comments/ttkkuv/whatsapp_web_doesnt_work_on_my_ipad_with_ios_12/

**Comment by hendranata** [comment]
sorry just couple days the error appear again..
no idea why..
any solution? because we use other WA apps like chrome,opera,firefox web browser .. all are normal..

**Comment by eneshecan** [comment]
Closing this due to being an upstream issue.
