### ISSUE TITLE
Can't open the app in Ubuntu 18.04

### ISSUE THREAD

**Issue by pqnhan** [eneshecan/whatsapp-for-linux#198]
**Description**
The application can't be opened after downloading.

**To Reproduce**
After downloading the AppImage build of the app and opening it on my Ubuntu 18.04, the app failed to open.
I tried opening it via Terminal Emulator and got the error message as shown below.

**Screenshots**
![image](https://user-images.githubusercontent.com/24197589/168302700-25d93cda-4be4-4a48-bce8-27437a73769c.png)

**Environment**
 - Ubuntu 18.04
 - AppImage
 - xfce4

**Comment by eneshecan** [comment]
Hi @pqnhan. We currently have a problem with the AppImage. Please see #160.
