### ISSUE TITLE
Package 'ayatana-appindicator3-0.1', required by 'virtual:world', not found

### ISSUE THREAD

**Issue by ndias** [eneshecan/whatsapp-for-linux#199]
**Description**

Compiling from source complains about not found  ayatana-appindicator3-0.1 but compiling the version 1.3.2 from source also  doesn't complains
-- Checking for module 'appindicator3-0.1'
--   Found appindicator3-0.1, version 12.10.0

**To Reproduce**
1. get the source from github version 1.4.3
2. follow the instructions to compile
3. See the error

**Environment**
 - Fedora 35 x86_64

**Comment by eneshecan** [comment]
Hi, @ndias. We switched to `libayatana-appindicator` from `libappindicator` and Fedora doesn't have the former AFAIK.
