### ISSUE TITLE
Link preview not working when we paste a link

### ISSUE THREAD

**Issue by nadimattari** [eneshecan/whatsapp-for-linux#201]
**Description**
The link preview card is being generated but there is no extra info in it. Page title is shown as the main domain address and the text shows the full address.

**To Reproduce**
1. Paste a link you want to share

**Expected behavior**
- First link preview one is what we get
- Second link preview is what we expect

![Screenshot from 2022-05-16 21-58-22](https://user-images.githubusercontent.com/1199419/168654316-5707eef4-c507-419b-a0de-696c2b739b0d.png)

**Screenshots**
![Screenshot from 2022-05-16 21-54-30](https://user-images.githubusercontent.com/1199419/168653655-ece60b25-10e6-4a90-a71a-a68a4af1226d.png)

**Environment**
 - Pop!_OS 
 - $ snap list | grep whatsapp
whatsapp-for-linux  1.4.3     35     latest/stable  nshecan
 - Gnome (42.0)
![Screenshot from 2022-05-16 20-12-49](https://user-images.githubusercontent.com/1199419/168653405-c573b4f4-eabb-489a-8deb-e518c79664be.png)

**Comment by luferequi** [comment]
This is also happening in the official WA web, it does not happen in the mobile version though.

**Comment by eneshecan** [comment]
Closing this due to being a behaviour of WhatsApp web
