### ISSUE TITLE
Notification icon dissapears imediately

### ISSUE THREAD

**Issue by WebShapedBiz** [eneshecan/whatsapp-for-linux#202]
**Description**
On elementaryOS 6.1 Linux, the red dot notification icon in the system panel disappears immediately after my desktop notification bubble disappears.

**To Reproduce**
1. When a new message arrives the red dot icon on the system panel is shown at the same time as the desktop notification bubble
2. When the desktop notification bubble disappears after a few seconds the red dot icon becomes the regular icon again as if I've read the message
3. The phone is on standby all the time and the message in the mobile app is still unread

**Expected behavior**
The red dot icon should be visible until the message gets read.

**Screenshots**

**Environment**
 - Distro elementaryOS 6.1
 - Package deb file from the GitHub
 - Desktop Environment or Window Manager Pantheon

Cheers.

**Comment by ocpalo** [comment]
The notification icon disappears under these circumsitances

* We Change the tray icon's status to normal again when the application window is raised which then we interpret as you've read all of the unread messages.
* If the Application window is already raised when notification is received.

For more information about why we prefer to do this way, please take a look at #155.

If the notification is disappeared even though you do not raise it when the application is in the tray, please let me know. I will take a look.

**Comment by WebShapedBiz** [comment]
Thank you @ocpalo for this clarification, I'll keep my eye on the notification icon when the app is in the tray.

Cheers.

**Comment by eneshecan** [comment]
Additionally what @ocpalo said, if your DE or notification daemon dismisses the notification, tray icon goes back to it's normal state again.
