### ISSUE TITLE
Flatpak version not running in Arch Linux

### ISSUE THREAD

**Issue by Dwahgon** [eneshecan/whatsapp-for-linux#211]
**Description**
The flatpak version of whatsapp for linux does not run. If I try to run it with `flatpak run com.github.eneshecan.WhatsAppForLinux` it outputs the error `logger: socket /dev/log: No such file or directory`. If I try to run it by clicking on the desktop icon or any other conventional way of running apps, the taskbar icon appears for a second, and disappears without opening the client.
The AUR version works fine.

**To Reproduce**
1. Download the Flatpak version of whatsapp-for-linux
2. Run the flatpak version of whatsapp for linux, either from command line or via the desktop icon

**Expected behavior**
It should run

**Screenshots**
![image](https://user-images.githubusercontent.com/47753585/178126302-f63f654a-df4f-4165-b568-0e5364913bc2.png)

**Environment**
 - Distro: Arch Linux
 - Kernel: 5.18.9-arch1-1
 - Package: Flatpak
 - Desktop Environment or Window Manager: KDE plasma 5.25.2
 - Flatpak Version: Flatpak 1.12.7

**Comment by Fenryrs** [comment]
I am also having this problem on Pop!_OS. The app wont start neither from the app launcher nor the `flatpak run com.github.eneshecan.WhatsAppForLinux` command. I installed through the Pop!_Shop.

![Screenshot](https://user-images.githubusercontent.com/94325544/180844507-34502da4-0f1f-4f0a-a087-43322619bab3.png)


- OS: Pop!_OS 22.04 LTS x86_64
- Kernel: 5.18.10-76051810-generic
- Package: Flatpak
- DE: GNOME 42.2

**Comment by eneshecan** [comment]
I think we need to check if the `/dev/log` is there before redirecting logs to the logger. I will take a look soon.

**Comment by eneshecan** [comment]
Maybe a workaround atm: https://askubuntu.com/questions/861227/dev-log-is-missing-how-do-i-fix

**Comment by eneshecan** [comment]
Fixed by 62ac660

**Comment by Master811129** [comment]
![Screenshot_20220808_224244-1](https://user-images.githubusercontent.com/37829730/183485667-e7e3236c-87e8-4afd-8d5b-0b4012341963.png)

mine has some warnings too. on Arch Linux.
could you please make an update thanks

**Comment by Master811129** [comment]
@eneshecan 
``` bash
$ flatpak info com.github.eneshecan.WhatsAppForLinux 

WhatsApp for Linux - An unofficial WhatsApp desktop application for Linux

          ID: com.github.eneshecan.WhatsAppForLinux
         Ref: app/com.github.eneshecan.WhatsAppForLinux/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.4.6
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 12.3?MB
     Runtime: org.gnome.Platform/x86_64/42
         Sdk: org.gnome.Sdk/x86_64/42

      Commit: 657809e0ceb110a1889a4ac773203ccd78977901710143fbe8655a466635da3b
      Parent: d25dd075b71ba62b399d036138e54b0187fc28e801bd368a7bcc68066b113dc8
     Subject: Bump version to 1.4.6 (8e2b8309)
        Date: 2022-08-06 14:17:01 +0000

```

**Comment by LucasGeisink** [comment]
> ![Screenshot_20220808_224244-1](https://user-images.githubusercontent.com/37829730/183485667-e7e3236c-87e8-4afd-8d5b-0b4012341963.png)
> 
> mine has some warnings too. on Arch Linux. could you please make an update thanks

Experiencing the same issue with exact same `flatpak info` output on Manjaro:

```
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.15.60-1-MANJARO (64-bit)
Graphics Platform: X11
```

**Comment by eneshecan** [comment]
I will take a look in a month as I am currently in vacation.

**Comment by LucasGeisink** [comment]
Appreciate the effort! Congratulations on getting married :smile:

**Comment by eneshecan** [comment]
Does this issue still persist? @Dwahgon

**Comment by Dwahgon** [comment]
> Does this issue still persist? @Dwahgon

I think the issue was fixed successfully. The application now runs as expected.
