### ISSUE TITLE
No Display with Whatsapp business account

### ISSUE THREAD

**Issue by wisdak** [eneshecan/whatsapp-for-linux#220]
**Description**
using normal whatsapp account operates normal, with out any issue, ... but recently i login with a business account which was also ok.. but the moment you click on view or edit catalog then add new item...then it freezes, nothing appears on the interface unless you close it and relaunch

**To Reproduce**
1. Go to 'your profile'
2. Scroll down to the bottom and click on view OR EDIT CATALOG
3. Click on add new item
4. See the error 'it becomes blank  '

**Expected behavior**
suppose to show you the items you have and an option to add new and edit.

**Screenshots**
![image](https://user-images.githubusercontent.com/98231918/182245959-74f6dd1c-6bc8-47c3-b7ed-d929d58041e2.png)

![image](https://user-images.githubusercontent.com/98231918/182246013-2135e7e9-c694-4272-82f6-a469ce0b126b.png)

after clicking on add new 
![image](https://user-images.githubusercontent.com/98231918/182246124-bb3c9abf-553b-4b20-861a-b05878965254.png)

**Environment**
 - Distro [Ubuntu Budgie 22.04 LTS x86_64  ]
 - Package [snap]
 - Desktop Environment or Window Manager [DE: Budgie 10.6.1 ]

**Comment by eneshecan** [comment]
Unfortunately, I don't have a business account to test this. Anyone with a business account please feel free to investigate this...

**Comment by wisdak** [comment]
am glad you gave a feedback........ it will be of great improvement if someone could test this......

**Comment by eneshecan** [comment]
@wisdak Can you maybe check the logs via running in terminal?

**Comment by wisdak** [comment]
alright..let me do that right away

**Comment by wisdak** [comment]
log file name is  000003.log

here is the content 

*\AE\CB#\00\00\00\00\00\00\00\00\00\00\00version1\00
namespace-O$%g\00\00\00\00\00\00\00\00\00\00\00next-map-id1Hnamespace-a4540397_e972_47ed_9d22_917ba7892ac4-https://web.whatsapp.com/0)\C2i9\00\00\00\00\00\00\00\00\00\00\00map-0-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00]$%<j\00\00\00\00\00\00\00\00\00\00\00\00Hnamespace-a4540397_e972_47ed_9d22_917ba7892ac4-https://web.whatsapp.com/\00map-0-storage_testX٪\E8g\00\00\00\00\00\00\00\00\00\00\00next-map-id2Hnamespace-90121c52_6611_49d4_bbc3_77be6cebe544-https://web.whatsapp.com/1\B7H'9\00
\00\00\00\00\00\00\00\00\00\00map-1-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00\B3BR\E4\A5\00\00\00\00\00\00\00\00\00\00\00\00map-1-storage_test map-1-forced-md-upgrade-completen\00u\00l\00l\00"map-1-show-md-upgrade-complete-msgn\00u\00l\00l\00map-1-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00\AB{q\EB\00\00\00\00\00\00\00\00\00\00\00\00 map-1-forced-md-upgrade-complete\00"map-1-show-md-upgrade-complete-msg\00map-1-storage_test map-1-forced-md-upgrade-completen\00u\00l\00l\00"map-1-show-md-upgrade-complete-msgn\00u\00l\00l\00map-1-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00<\D83p\EB\00\00\00\00\00\00\00\00\00\00\00\00 map-1-forced-md-upgrade-complete\00"map-1-show-md-upgrade-complete-msg\00map-1-storage_test map-1-forced-md-upgrade-completen\00u\00l\00l\00"map-1-show-md-upgrade-complete-msgn\00u\00l\00l\00map-1-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00\B7;\90\9F\BE\00\00\00\00\00\00\00\00\00\00\00\00 map-1-forced-md-upgrade-complete\00"map-1-show-md-upgrade-complete-msg\00map-1-storage_test map-1-forced-md-upgrade-completen\00u\00l\00l\00"map-1-show-md-upgrade-complete-msgn\00u\00l\00l\00\D6l\F4\C89\00 \00\00\00\00\00\00\00\00\00\00map-1-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00\F0bǂ\BE\00!\00\00\00\00\00\00\00\00\00\00\00 map-1-forced-md-upgrade-complete\00"map-1-show-md-upgrade-complete-msg\00map-1-storage_test map-1-forced-md-upgrade-completen\00u\00l\00l\00"map-1-show-md-upgrade-complete-msgn\00u\00l\00l\00\A0\92\BAw9\00&\00\00\00\00\00\00\00\00\00\00map-1-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00
eذ\00'\00\00\00\00\00\00\00\00\00\00\00Hnamespace-90121c52_6611_49d4_bbc3_77be6cebe544-https://web.whatsapp.com/\00 map-1-forced-md-upgrade-complete\00"map-1-show-md-upgrade-complete-msg\00map-1-storage_test\D4\E55g\00+\00\00\00\00\00\00\00\00\00\00next-map-id3Hnamespace-08d876cc_2ef2_4584_89a9_a9c03e534ad3-https://web.whatsapp.com/2\9D\E8\BA\DF9\00-\00\00\00\00\00\00\00\00\00\00map-2-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00\C1\9F\901j\00.\00\00\00\00\00\00\00\00\00\00\00Hnamespace-08d876cc_2ef2_4584_89a9_a9c03e534ad3-https://web.whatsapp.com/\00map-2-storage_test\A5Ӧ_g\000\00\00\00\00\00\00\00\00\00\00next-map-id4Hnamespace-44d60cb2_7dc2_4711_9aab_c4e2339c4f68-https://web.whatsapp.com/3^\DBޝ9\002\00\00\00\00\00\00\00\00\00\00map-3-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00\9B\D3L\B6\003\00\00\00\00\00\00\00\00\00\00\004\ABg\003\00\00\00\00\00\00\00\00\00\00next-map-id5Hnamespace-46fc6c89_f5b1_40f4_af43_6f3c886e2591-https://web.whatsapp.com/4\EE˩\A09\005\00\00\00\00\00\00\00\00\00\00map-4-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00g\B1߂j\006\00\00\00\00\00\00\00\00\00\00\00Hnamespace-46fc6c89_f5b1_40f4_af43_6f3c886e2591-https://web.whatsapp.com/\00map-4-storage_test\9Cj\D89g\008\00\00\00\00\00\00\00\00\00\00next-map-id6Hnamespace-492957a2_c687_4063_b51d_96768fb2b959-https://web.whatsapp.com/5H刷9\00:\00\00\00\00\00\00\00\00\00\00map-5-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00E@\92^g\00;\00\00\00\00\00\00\00\00\00\00next-map-id7Hnamespace-3caf07f3_b8bf_46ed_b39c_ab6da23c0c32-https://web.whatsapp.com/6\E8\D6\BE9\00=\00\00\00\00\00\00\00\00\00\00map-6-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00o\DE,g\00>\00\00\00\00\00\00\00\00\00\00next-map-id8Hnamespace-68994832_4ace_4751_9ef9_6544ee5479af-https://web.whatsapp.com/7X}\949\00@\00\00\00\00\00\00\00\00\00\00map-7-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00j\87\DDig\00A\00\00\00\00\00\00\00\00\00\00next-map-id9Hnamespace-f1712f61_00c5_4998_9e66_2a367c43f935-https://web.whatsapp.com/8R\A5\E1\AA9\00C\00\00\00\00\00\00\00\00\00\00map-8-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00\98\88j\00D\00\00\00\00\00\00\00\00\00\00\00Hnamespace-f1712f61_00c5_4998_9e66_2a367c43f935-https://web.whatsapp.com/\00map-8-storage_test\FCtw\EAh\00F\00\00\00\00\00\00\00\00\00\00next-map-id10Hnamespace-58395630_7998_4c67_9636_9a7a6ffadb89-https://web.whatsapp.com/9gN)\889\00H\00\00\00\00\00\00\00\00\00\00map-9-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00Qfi\00I\00\00\00\00\00\00\00\00\00\00next-map-id11Hnamespace-476df673_f700_45c5_8996_6f6aaa23f00b-https://web.whatsapp.com/10Qp\C3i:\00K\00\00\00\00\00\00\00\00\00\00map-10-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00	\D2zk\00L\00\00\00\00\00\00\00\00\00\00\00Hnamespace-476df673_f700_45c5_8996_6f6aaa23f00b-https://web.whatsapp.com/\00map-10-storage_test\E2hLi\00N\00\00\00\00\00\00\00\00\00\00next-map-id12Hnamespace-8045ce2c_7158_4cdb_aaf4_cfa75b537aaa-https://web.whatsapp.com/11j\DA}:\00P\00\00\00\00\00\00\00\00\00\00map-11-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00P:!lk\00Q\00\00\00\00\00\00\00\00\00\00\00Hnamespace-8045ce2c_7158_4cdb_aaf4_cfa75b537aaa-https://web.whatsapp.com/\00map-11-storage_testX\AEQ\C1i\00S\00\00\00\00\00\00\00\00\00\00next-map-id13Hnamespace-f49e0700_b23a_49b6_bf5e_59f2433badb7-https://web.whatsapp.com/12:\E6\F5\EC:\00U\00\00\00\00\00\00\00\00\00\00map-12-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00\E4E\F5\A8k\00V\00\00\00\00\00\00\00\00\00\00\00Hnamespace-f49e0700_b23a_49b6_bf5e_59f2433badb7-https://web.whatsapp.com/\00map-12-storage_test\F0\9A/\8Ei\00X\00\00\00\00\00\00\00\00\00\00next-map-id14Hnamespace-473be291_73ad_4e2a_8e6e_4beb44d1ea0d-https://web.whatsapp.com/13[\AC\9E\9C:\00Z\00\00\00\00\00\00\00\00\00\00map-13-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00\C7D\81\C0\00[\00\00\00\00\00\00\00\00\00\00\00\E91\CAk\00[\00\00\00\00\00\00\00\00\00\00\00Hnamespace-473be291_73ad_4e2a_8e6e_4beb44d1ea0d-https://web.whatsapp.com/\00map-13-storage_test\B3>\ABoi\00]\00\00\00\00\00\00\00\00\00\00next-map-id15Hnamespace-b4e70c18_8be5_455f_9b9e_f08d99c51be6-https://web.whatsapp.com/14[\BD\E5	:\00_\00\00\00\00\00\00\00\00\00\00map-14-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00ȟ\C2\FAk\00`\00\00\00\00\00\00\00\00\00\00\00Hnamespace-b4e70c18_8be5_455f_9b9e_f08d99c51be6-https://web.whatsapp.com/\00map-14-storage_test\DA\ED\D2\CBi\00b\00\00\00\00\00\00\00\00\00\00next-map-id16Hnamespace-05f6dbbd_5a40_40e6_b9c7_105a6555a41d-https://web.whatsapp.com/15K8:\00d\00\00\00\00\00\00\00\00\00\00map-15-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00s\00t\00\B9\00\F7k\00e\00\00\00\00\00\00\00\00\00\00\00Hnamespace-05f6dbbd_5a40_40e6_b9c7_105a6555a41d-https://web.whatsapp.com/\00map-15-storage_test\9CLn7i\00g\00\00\00\00\00\00\00\00\00\00next-map-id17Hnamespace-7fec0001_697c_48ec_8c1c_59ad313e6e4c-https://web.whatsapp.com/16-\F2\98\F2:\00i\00\00\00\00\00\00\00\00\00\00map-16-storage_tests\00t\00o\00r\00a\00g\00e\00_\00t\00e\00\00\00\00\00

**Comment by wisdak** [comment]
But i just tried opening it using the browser and i realize is also doing the same thing....

So i guess its not from the App rather a general thing

**Comment by eneshecan** [comment]
Yeah, probably on WhatsApp web side.
