### ISSUE TITLE
AUR Package not working on arch linux

### ISSUE THREAD

**Issue by Master811129** [eneshecan/whatsapp-for-linux#221]
**Description**
```
<13>Aug 13 11:41:59 whatsapp-for-linux[12694]: SettingMap: terminate called after throwing an instance of 'Glib::ConvertError'
Aborted (core dumped)
```

**To Reproduce**
1. install: `$ yay -S whatsapp-for-linux`
2. run `whatsapp-for-linux`
3. See the error:
```
<13>Aug 13 11:41:59 whatsapp-for-linux[12694]: SettingMap: terminate called after throwing an instance of 'Glib::ConvertError'
Aborted (core dumped)
```

**Expected behavior**
The app should open up.

**Screenshots**
![Screenshot_20220813_115745](https://user-images.githubusercontent.com/37829730/184473821-3053b133-45af-4b3e-b14c-25d7d25c9ec0.png)

**Environment**
 - Distro [Arch BTW Linux]
 - Package [AUR (pacman)]
 - Desktop Environment or Window Manager [KDE]

**Comment by eneshecan** [comment]
Your locale configuration might be broken. Try to regenerate them.

**Comment by Master811129** [comment]
I don't know if it was broken or not. But I changed the locale setting in KDE plasma settings app and it worked. before that My locale was something like this. 
```
$ locale
LANG=C
LC_CTYPE=C
LC_NUMERIC=C
LC_TIME=C
LC_COLLATE=C
LC_MONETARY=C
LC_MESSAGES=C
LC_PAPER=C
LC_NAME=C
LC_ADDRESS=C
LC_TELEPHONE=C
LC_MEASUREMENT=C
LC_IDENTIFICATION=C
LC_ALL=
```
![Screenshot_20220814_110802](https://user-images.githubusercontent.com/37829730/184525584-21af2b33-6cc4-4f82-bab0-83f2fe569951.png)


after i changed the settings 

```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
![Screenshot_20220814_110825](https://user-images.githubusercontent.com/37829730/184525588-d714ecb3-59ba-40f1-92ff-dcf174126fba.png)

**Comment by eneshecan** [comment]
Closing this then.
