### ISSUE TITLE
mouse button functions in systray

### ISSUE THREAD

**Issue by h45h1r** [eneshecan/whatsapp-for-linux#222]
I was wondering if you could change what different mouse buttons do in systray (just like how telegram and gammy do it)
left click : minimizes and restores the window
right click : shows menu

**Comment by eneshecan** [comment]
Unfortunately, ayatana-appindicator doesn't have click events and you can only assign menus to it. It's not possible to do this without a hacky workaround or switching to another library.

**Comment by eneshecan** [comment]
And, we can save the fullscreen status in config if you could create another issue.
