### ISSUE TITLE
WhatsApp For Linux starts but doesnt load, keeps in loading screen forever.

### ISSUE THREAD

**Issue by dCo3lh0** [eneshecan/whatsapp-for-linux#223]
**Description**
Whatsapp starts but doesnt load, keeps in loading screen forever.

**To Reproduce**
1. Start WhatsApp For Linux
2. Window opens normally
3. Wait till load completes, forever.

**Expected behavior**
Finish Loading and shows WhatsApp Web normally

**Screenshots**
![2022-08-30_17-28](https://user-images.githubusercontent.com/21119505/187537035-f9de4932-bcca-4d14-9d4a-b1a0b3e01be4.png)

**Environment**
 - Linux Mint Debian Edition 5 (Debian 11 Bullseye Base)
 - Flatpak
 - Cinnamon 5.4.11 with Mutter Window Manager

**Comment by eneshecan** [comment]
Could you please try to unlink your PC and remove the folder `~/.cache/whatsapp-for-linux`?

**Comment by dCo3lh0** [comment]
Its missing since i uninstalled whatsapp for linux, installed again, maybe removing erased this folder and installing again didnt create, i even tried the appimage version without much luck.

**Comment by eneshecan** [comment]
It should create this folder automatically. It seems that somehow webkit doesn't start on your PC. Could you please send some logs by running in terminal?

**Comment by dCo3lh0** [comment]
does this message has something to do with this?

`** (process:11406): WARNING **: 19:54:35.713: Error writing credentials to socket: Error sending message: Broken pipe
logger: soquete /dev/log: Arquivo ou diretório inexistente`

**Comment by dCo3lh0** [comment]
How do i do the debug? just launching from the terminal, if it is, then the only message showing me is this /dev/log error, nothing more nothing less, the error keeps happening for me.

**Comment by eneshecan** [comment]
I'll take a look soon, might be related to flatpak permissions.

**Comment by dCo3lh0** [comment]
oh really, than flatseal solves it im gonna look at it

**Comment by dCo3lh0** [comment]
it didnt solve it, but i tried it at least.

**Comment by eneshecan** [comment]
Working on it atm...

**Comment by eneshecan** [comment]
Should be fixed now with a nasty workaround... Please try installing the build;
`flatpak install https://dl.flathub.org/build-repo/109582/com.github.eneshecan.WhatsAppForLinux.flatpakref`
until the latest build is published and let me know.

**Comment by dCo3lh0** [comment]
Yeah i did update, at first it wasnt working yet so i unninstalled, removed all settings and configs from ~/.var/app/com.github.eneshecan.WhatsAppForLinux, installed, did the QR Code sync all again and its working now. Thanks!

**Comment by eneshecan** [comment]
Closing this then.
