### ISSUE TITLE
Slow responding even without hardware acceleration

### ISSUE THREAD

**Issue by gelu22** [eneshecan/whatsapp-for-linux#225]
**Description**
My application is slow. You can especially notice it when switching between conversations. 
I turned off hardware acceleration, but with little effect.

**To Reproduce**
-

**Screenshots**
-

**Environment**
 - Linux Mint 20.3
 - Snapcraft
 - Cinnamon 5.2.7
 - WhatsApp 1.4.6

**Comment by i-am-ecc** [comment]
I've been into this problem aswell - hardware acceleration set to "Never".

**Comment by eneshecan** [comment]
Cannot find a solution for this. Probably an upstream issue as I was able to reproduce with Epiphany as well.

**Comment by eneshecan** [comment]
The issue is gone for me on Arch Linux. Please try the latest release and let me know.

**Comment by gelu22** [comment]
Now it works like lightning - thanks!  
I will use it for a few days, if anything changes, I will let you know. I have hardware acceleration enabled.

**Comment by i-am-ecc** [comment]
Installed 1.4.7 now and set hardware acceleration to "On Demand". Works like a charm now.
