### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by rschnapka** [eneshecan/whatsapp-for-linux#226]
Hello all,
I just installed your "whatsapp-for-linux" and cannot start the app. When calling the app from command line I receive the following errors:
(process:2535): Gtk-WARNING **: 09:59:07.010: Locale not supported by C library.
        Using the fallback 'C' locale.
<13>Sep 26 09:59:07 whatsapp-for-linux[2607]: Gtk-Message: 09:59:07.059: Failed to load module "colorreload-gtk-module"
<13>Sep 26 09:59:07 whatsapp-for-linux[2607]: Gtk-Message: 09:59:07.059: Failed to load module "window-decorations-gtk-module"
<13>Sep 26 09:59:07 whatsapp-for-linux[2607]: 
<13>Sep 26 09:59:07 whatsapp-for-linux[2607]: ** (whatsapp-for-linux:2535): WARNING **: 09:59:07.106: Could not open /sys/class/dmi/id/chassis_type: Failed to open file ?/sys/class/dmi/id/chassis_type?: Permission denied
<13>Sep 26 09:59:07 whatsapp-for-linux[2607]: 
<13>Sep 26 09:59:07 whatsapp-for-linux[2607]: ** (whatsapp-for-linux:2535): WARNING **: 09:59:07.106: Could not open /sys/firmware/acpi/pm_profile: Failed to open file ?/sys/firmware/acpi/pm_profile?: Permission denied
<13>Sep 26 09:59:07 whatsapp-for-linux[2607]: SettingMap: terminate called after throwing an instance of 'Glib::ConvertError'
Aborted (core dumped)

With both files having permission issues, read permission for owner, group, and others is given (mask 100444)
I have a Kubuntu 22.04 setup with:
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-48-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3-7100U CPU @ 2.40GHz
Memory: 7,6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620
If this helps...

best regards
Rudolf

**Comment by eneshecan** [comment]
This will be fixed with the next release. Please advise #154 for now.
