### ISSUE TITLE
Simplify Config & Preferences

### ISSUE THREAD

**Issue by eneshecan** [eneshecan/whatsapp-for-linux#229]
Simplify the Settings class and rename config file groups and keys for better categorization and convention.

This breaks backward compatibility with old config files. So, removing your config file and letting the app recreate it for you is advised.

**Comment by eneshecan** [comment]
Implemented with 2faa945

**Comment by i-am-ecc** [comment]
I just updated from 1.4.7 to 1.5.0 and, since then, the app doesn't remember any setting after restart - I even deleted the old settings.conf file and tried to recreate it, but it just gives me a 0kb file and I don't know what to do from there.

**Comment by eneshecan** [comment]
@i-am-ecc Could you please send the coredump with the debug build or use gdb to find out where it breaks?

**Comment by i-am-ecc** [comment]
This is what happens:

`<13>Oct 31 11:01:43 whatsapp-for-linux[26179]: SettingMap: Key file does not have group “web”, returning default value: 1
<13>Oct 31 11:01:44 whatsapp-for-linux[26179]: SettingMap: Key file does not have group “general”, returning default value: 1
<13>Oct 31 11:01:44 whatsapp-for-linux[26179]: SettingMap: Key file does not have group “web”, returning default value: 0
<13>Oct 31 11:01:44 whatsapp-for-linux[26179]: SettingMap: Key file does not have group “general”, returning default value: 0
<13>Oct 31 11:01:44 whatsapp-for-linux[26179]: SettingMap: Key file does not have group “general”, returning default value: 1
<13>Oct 31 11:01:44 whatsapp-for-linux[26179]: SettingMap: Key file does not have group “general”, returning default value: 0
<13>Oct 31 11:01:44 whatsapp-for-linux[26179]: SettingMap: Key file does not have group “general”, returning default value: 0
Falha de segmentação
`

**Comment by i-am-ecc** [comment]
OK, I found out what happened: the settings.conf file is case-sensitive, and instead of [general] and [web], it has [General] and [Web]. Problem solved.
