### ISSUE TITLE
Reports itself as MacOS to Whatsapp

### ISSUE THREAD

**Issue by guneetnarula** [eneshecan/whatsapp-for-linux#23]
Once I logged into the client, Whatsapp on my phone notified me that I logged in through MacOS. But I am on Ubuntu 20.04. Is this a known issue, or related to something else that user can fix themselves?

**Comment by eneshecan** [comment]
Yes, I am aware of this. This is weird and might be related to webkit2 or whatsapp's api. Honestly, I ignored this for now since it doesn't affect any functionality and I don't have much time. However, please feel free to investigate and contribute if you find anything :)

**Comment by guneetnarula** [comment]
Thanks for the response! Maybe it is the user.agent property in webkit2, not sure. I'll have a look when I have time

**Comment by chinmaya1011** [comment]
It's because of WebKit. If you use Epiphany browser (which also runs on WebKit) to log into WhatsApp it says Mac OS. Facebook says "Safari for Linux".
