### ISSUE TITLE
Preferences window is not attached to the main window

### ISSUE THREAD

**Issue by musiclover382** [eneshecan/whatsapp-for-linux#236]
**Description**
Preferences window can be moved freely in the screen, indipendently from the main window

**To Reproduce**
1. Open the preferences window

**Expected behavior**
Like in most gnome apps, I'd expect the main window to move with the preferences window, and the latter to be always centered. Also, the main window should be uninteractive while the preferences window is open

**Comment by eneshecan** [comment]
Fixed by f57239a

**Comment by musiclover382** [comment]
That worked indeed. Thanks!
