### ISSUE TITLE
[ Ubuntu 22.04.1 / Wayland / DEB ] Not saving settings

### ISSUE THREAD

**Issue by scoony** [eneshecan/whatsapp-for-linux#244]
Hello,

I've installed your debian file and it's working perfectly ... but everytime i try to change the settings it's not saved so when i restart the app no start-in-tray or close-in-tray.

I found a way to fix manually by reading your source code.

file ~/.config/whatsapp-for-linux/settings.conf:
```
[web]
allow-permissions=true  
[general]
start-in-tray=true
close-to-tray=true
```

**Comment by eneshecan** [comment]
Seems like the app crashes on exit. Is there any chance that you debug the application and tell me where it breaks?

**Comment by scoony** [comment]
The syslog when I close it:
Kernel: 5.15.0-52 (latest Ubuntu available)
```
Nov  2 18:14:37 Serveur-NAS gnome-shell[804819]: Window manager warning: Ping serial 58988288 was reused for window W6, previous use was for window W95.
Nov  2 18:14:37 Serveur-NAS gnome-shell[804819]: message repeated 12 times: [ Window manager warning: Ping serial 58988288 was reused for window W6, previous use was for window W95.]
Nov  2 18:14:43 Serveur-NAS kernel: [58995.464033] whatsapp-for-li[1337511]: segfault at 0 ip 00007fc02b48e386 sp 00007ffc0c312f08 error 4 in libwebkit2gtk-4.0.so.37.56.12[7fc02af3b000+274c000]
Nov  2 18:14:43 Serveur-NAS kernel: [58995.464040] Code: 89 e7 ff d3 eb d2 e8 d9 d4 ab ff 66 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 8b 47 28 48 8d 15 c1 2a 00 00 48 8b b8 a8 01 00 00 <48> 8b 07 48 8b 40 30 48 39 d0 75 06 31 c0 c3 0f 1f 00 ff e0 66 0f
Nov  2 18:14:43 Serveur-NAS systemd[2649]: app-gnome-com.github.eneshecan.WhatsAppForLinux-1337511.scope: Consumed 29.229s CPU time.
```

**Comment by eneshecan** [comment]
This doesn't help a lot. Can you send the coredump if you have coredumpctl available on your system?

**Comment by scoony** [comment]
![Capture d’écran du 2022-11-03 01-06-50](https://user-images.githubusercontent.com/7669098/199624923-3c5b648a-6a87-4740-9801-d93d127b57db.png)

Dunno if it's gonna be helpful, got nothing in /var/crash... apport is enabled and i even tried
`ulimit -c unlimited`
and
`service apport start force_start=1`

**Comment by scoony** [comment]
I had some errors apparently due to the lack of variables in the conf...
`<13>Nov  3 01:11:50 whatsapp-for-linux[1821302]: SettingMap: Key file does not have key “start-minimized” in group “general”, returning default value: 0`

So I've edited manually the file and no more errors, still not saving my settings when using the app.
```
[web]
allow-permissions=true
hw-accel=1

[general]
start-in-tray=false
close-to-tray=true
start-minimized=true
```

**Comment by scoony** [comment]
I forgot, when I installed there were no [general] settings, only [web] in the file.

**Comment by scoony** [comment]
Ok, i found a way ... sorry never dumped before.

Here is the dump:
[WhatsApp.dump](https://www.mediafire.com/file/amiekcmmz0ymbbg/whatsapp.dump/file)

**Comment by eneshecan** [comment]
Thank you! FYI, those messages are not really errors but info indicating that you didn't change the setting, so it returns the default value since it doesn't exist in the config.

**Comment by cloudmaker97** [comment]
I had the same issue but i found a way to get the settings saved without editing config files:

1. Open the 'Preferences' window and make your changes
2. Close the 'Preferences' window

**Comment by jrodriguer** [comment]
Same way for 'Autostart' preference? the rest of the options it's OK following. this steps (issue comment):

1. Open the 'Preferences' window and make your changes.
2. Close the 'Preferences' window.
3. Quit the Application over the same Menu where you found the 'Preferences' Button.

**Comment by niels-beier** [comment]
> I had the same issue but i found a way to get the settings saved without editing config files:
> 
>     1. Open the 'Preferences' window and make your changes
> 
>     2. Close the 'Preferences' window
> 
>     3. Quit the Application over the same Menu where you found the 'Preferences' Button
> 
> 
> 
> After a restart all settings are applied.

Didn't work for me on Ubuntu 22.04 and 23.04. Output always tells:

```
<13>May  2 22:45:48 whatsapp-for-linux[426064]: SettingMap: Key file does not have group “web”, returning default value: 1
<13>May  2 22:45:48 whatsapp-for-linux[426064]: SettingMap: Key file does not have group “web”, returning default value: 0
<13>May  2 22:45:48 whatsapp-for-linux[426064]: SettingMap: Key file does not have group “general”, returning default value: 1
<13>May  2 22:45:48 whatsapp-for-linux[426064]: SettingMap: Key file does not have group “web”, returning default value: 0
```
and
```
<13>May  2 22:45:48 whatsapp-for-linux[426064]: SettingMap: Key file does not have group “general”, returning default value: 0
<13>May  2 22:45:48 whatsapp-for-linux[426064]: SettingMap: Key file does not have group “general”, returning default value: 1
<13>May  2 22:45:48 whatsapp-for-linux[426064]: SettingMap: Key file does not have group “general”, returning default value: 0
<13>May  2 22:45:48 whatsapp-for-linux[426064]: SettingMap: Key file does not have group “general”, returning default value: 0
<13>May  2 22:45:48 whatsapp-for-linux[426064]: SettingMap: Key file does not have group “appearance”, returning default value: 0
```
Changing values manually in the config file also doesn't seem to have an impact.

**Comment by samirkushwaha** [comment]
+1 to this.
Facing this in the latest 1.6.3 snap running on Ubuntu 23.04.
Everytime, I close and reopen the app, it asks for notifications permissions and the minimise to tray toggle is unset.
