### ISSUE TITLE
Mic not enabled

### ISSUE THREAD

**Issue by DevDorrejo** [eneshecan/whatsapp-for-linux#252]
**Description**
Can use the mic for voice chat, the Mic icon not appear where it have to appear.

**Environment**
 - Distro: openSUSE Tumbleweed
 - Package: Flatpak
 - Desktop Environment or Window Manager: KDE Plasma

**Comment by Vistaus** [comment]
I have the same issue on Tumbleweed, but I do use the package from OPI.

I wonder why this feature is marked as upstream and not planned, 'cause WhatsWeb on Ubuntu Touch - which is pretty much the same app as this one - does have mic support.
