### ISSUE TITLE
Find Russian translation and icons here

### ISSUE THREAD

**Issue by Aalexeey** [eneshecan/whatsapp-for-linux#260]
Hi,
Find attached Russian .po file.
[ru.po.txt](https://github.com/eneshecan/whatsapp-for-linux/files/10280967/ru.po.txt)

**Comment by eneshecan** [comment]
Wait, I thought we had a russian translation. Here https://github.com/eneshecan/whatsapp-for-linux/blob/master/po/ru.po ? Is this an update then?

**Comment by Aalexeey** [comment]
Didn't know that, some body was faster :-), any way find some modified icons here. I have Olive color theme, default icon is invisible in the trey.
[icons.tar.gz](https://github.com/eneshecan/whatsapp-for-linux/files/10284621/icons.tar.gz)

**Comment by eneshecan** [comment]
We don't need something with the Russian translation atm and I don't understand what the icons are for and what is the issue. Please create another issue with a clear explanation.
