### ISSUE TITLE
Dark theme not appearing for window border in Linux Mint 21 Vanessa, Flatpak.

### ISSUE THREAD

**Issue by BrainKicker** [eneshecan/whatsapp-for-linux#262]
**Description**
Dark theme not appearing for window border in Linux Mint 21 Vanessa, Flatpak.

**To Reproduce**
1. Install Linux Mint 21 Vanessa.
2. Install app through Flatpak.
3. Go to "Preferences".
4. Choose "Appearence" -> "Prefer Dark Theme".

**Expected behavior**
Expected dark window borders.

**Screenshots**

![Screenshot_20221227_023050-obfuscated](https://user-images.githubusercontent.com/30545094/209588488-0b294f54-76de-4f45-a7b4-fc4e8087f3fc.png)

![Screenshot_20221227_023451](https://user-images.githubusercontent.com/30545094/209588491-ad6a4073-1e0e-4674-a62d-bab99dfcd13d.png)

**Environment**
 - Distro - Linux Mint 21 Vanessa
 - Package - Flatpak com.github.eneshecan.WhatsAppForLinux 1.5.1 stable
 - Desktop Environment or Window Manager - Cinnamon

**Comment by haggen88** [comment]
Related > https://github.com/linuxmint/mint21.1-beta/issues/61

**Comment by BrainKicker** [comment]
Installing corresponding theme fixed this.
https://github.com/linuxmint/mint21.1-beta/issues/61
