### ISSUE TITLE
H

### ISSUE THREAD

**Issue by cesctiger** [eneshecan/whatsapp-for-linux#264]
**Description**

**To Reproduce**
4. See the error

**Expected behavior**

**Screenshots**

**Environment**
 - Distro [e.g. Ubuntu, Arch Linux]
 - Package [e.g. snap, debian]
 - Desktop Environment or Window Manager [e.g. Gnome, i3wm]

**Comment by cesctiger** [comment]
Wow

**Comment by eneshecan** [comment]
?!
