### ISSUE TITLE
Tray icon is missing

### ISSUE THREAD

**Issue by christian179717** [eneshecan/whatsapp-for-linux#266]
**Description**
No to WhatsApp connected tray icon available.

**Expected behavior**
Something like this: 
![grafik](https://user-images.githubusercontent.com/89655752/211406679-2b8e6a48-9fb5-4d59-97f4-218450ddd5ec.png)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/89655752/211406725-0635158b-5fa1-4ff4-a6b3-485708083245.png)

**Environment**
 - Distro Mint
 - Package snap
 - Cinnamon

**Comment by eneshecan** [comment]
Hi @christian179717. Thanks for the report. Please see #98.
