### ISSUE TITLE
Use different compression mode for deb package

### ISSUE THREAD

**Issue by filhocf** [eneshecan/whatsapp-for-linux#267]
In Debian, dpkg can't use zstd compression algoritm, so we can't install the debian package.

Can you change the compression algoritm when make the deb package?

Bug report in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664

The error:
```
$ LANG=C sudo apt install ./whatsapp-for-linux_1.5.1_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'whatsapp-for-linux' instead of './whatsapp-for-linux_1.5.1_amd64.deb'
The following NEW packages will be installed:
  whatsapp-for-linux
0 upgraded, 1 newly installed, 0 to remove and 16 not upgraded.
Need to get 0 B/112 kB of archives.
After this operation, 398 kB of additional disk space will be used.
Get:1 /home/claudio/Downloads/whatsapp-for-linux_1.5.1_amd64.deb whatsapp-for-linux amd64 1.5.1 [112 kB]
dpkg-deb: error: archive '/home/claudio/Downloads/whatsapp-for-linux_1.5.1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /home/claudio/Downloads/whatsapp-for-linux_1.5.1_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /home/claudio/Downloads/whatsapp-for-linux_1.5.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by eneshecan** [comment]
Hi @filhocf. Thanks for this! Let me check what is the recommended compression type and change that.

**Comment by eneshecan** [comment]
I just checked our code and saw that we don't specify the compression type at all. However, we build for Ubuntu which I assume is not compatible with Debian. I believe building for Debian should solve the issue or we can try to set the compression type explicitly.

**Comment by filhocf** [comment]
Maybe this site can help you.

https://stackoverflow.com/questions/71196872/how-do-i-build-a-deb-without-zstd-compression-in-ubuntu-21-10



Em qua., 11 de jan. de 2023 às 12:40, Xeco ***@***.***>
escreveu:

**Comment by eneshecan** [comment]
Thanks, I'll take a look. If anyone wants to make PR until then, it's appreciated as well!

**Comment by WolfganP** [comment]
Same error here installing in MXlinux, I'll appreciate if you can change the compression method for the next release.

**Comment by filhocf** [comment]
I'm waiting for a new version as soon possible, including pt-BR language. ;-)

**Comment by eneshecan** [comment]
Well, the new release is out. Check out the releases section.

**Comment by WolfganP** [comment]
@eneshecan thx a lot for the new release. Just to confirm it installs OK (but a new issue `GLIBC_2.34 not found` appeared when trying to run it  (will try to troubleshoot it later, it wasn't present in my previously installed version)

**Comment by eneshecan** [comment]
@WolfganP Just tested on my Debian VM. Same problem for me...

**Comment by eneshecan** [comment]
For now, I compiled a deb package manually on Debian to make this work. Please find it here: https://github.com/eneshecan/whatsapp-for-linux/releases/tag/v1.5.2.

Could someone please create a separate issue for this?

**Comment by filhocf** [comment]
To me, installed fine this package. I've again whatsapp-for-linux in my desktop. Thank you, @eneshecan. :pray:

**Comment by WolfganP** [comment]
> For now, I compiled the package manually on Debian to make this work. Please find it here: https://github.com/eneshecan/whatsapp-for-linux/releases/download/v1.5.2/whatsapp-for-linux_1.5.2_amd64_debian.deb
> 
> Could someone please create a separate issue for this?

Package installed fine and app working again. Thx a lot @eneshecan !

New tracking issue https://github.com/eneshecan/whatsapp-for-linux/issues/273 created as per your request.
