### ISSUE TITLE
Unable to Paste Clipboard Images in Whatsapp for Linus

### ISSUE THREAD

**Issue by stephenaustin** [eneshecan/whatsapp-for-linux#268]
**Description**
Unable to paste images on clipboard into the message pane on Whatsapp-for-Linux

**To Reproduce**
1. Copy any image (eg from Flameshot). 
2. Attempt to paste it into the message pane of recipient on Whatsapp-for-Linux
3. Nothing happens

**Expected behavior**
The image should appear in the message pane. 

**Environment**
Linux pop-os 6.0.12-76060006-generic #202212290932~1671652965~22.04~452ea9d SMP PREEMPT_DYNAMIC Wed D x86_64 x86_64 x86_64 GNU/Linux

 - Ubuntu
 -  - Package snap
 - Desktop Environment Gnome

**Comment by eneshecan** [comment]
Hi, please see #79

**Comment by stephenaustin** [comment]
> Hi, please see #79

OK! Thanks.
