### ISSUE TITLE
Can't use clipboard to insert screenshots (KDE)

### ISSUE THREAD

**Issue by emsofo** [eneshecan/whatsapp-for-linux#271]
**Description**
Using 1.5.1 under Mageia Linux - KDE desktop

When using WhatsApp web under Forfox - I can take a screenshot and copy it to clipboard - then re-paste it into a WhatsApp conversation - with your tool - I can't.

**To Reproduce**
1. Create screenshot and save to clipboard (using "Spectacle" for screenshot)
2. switch to WhatsApp for Linux 1.5.1 and try to paste the clipboard contents into a conversation - nothing happens
3. If same is done with WhatsApp web under Forefox it works (same system and clipboard (Plasma clipboard)
4. See the error

**Expected behavior**
When copying and pasting clipboard contents - should be able to paste into WhatsApp for Linux 1.5.1

**Screenshots**
![image](https://user-images.githubusercontent.com/107464168/212940270-6f18f26f-45ce-4bab-9223-705e720e57fe.png)

**Environment**
 - Mageia Cauldron 
 - Package whatsapp-for-linux-1.5.1-1.mga9
 - Desktop Environment or Window Manager - KDE Plasma

**Comment by hems** [comment]
same happens on ArchLinux / Manjaro.

any updates on this?

**Comment by eneshecan** [comment]
Please see #79

**Comment by emsofo** [comment]
Sorry to hear that!  Otherwise your program is very good - Thx anyway.
