### ISSUE TITLE
"GLIBC_2.34 not found" appeared when trying to run the program, .deb installed OK

### ISSUE THREAD

**Issue by WolfganP** [eneshecan/whatsapp-for-linux#273]
**Description**
v.1.5.2 .deb installed OK. When trying to run it on debian bullseye "GLIBC_2.34 not found" appeared and program exited,

Solved with special build https://github.com/eneshecan/whatsapp-for-linux/releases/download/v1.5.2/whatsapp-for-linux_1.5.2_amd64_debian.deb at https://github.com/eneshecan/whatsapp-for-linux/issues/267#issuecomment-1403280515

**Environment**
 - Distro MXlinux 21.3, debian bullseye
 - Package v1.5.2 deb
 - Desktop Environment or Window Manager XFCE

**Comment by eneshecan** [comment]
Fixed by 34699e4dd76667ddcadd91af69edd58b3872fca8 and available with the 1.5.3 release.

Beware that this is only expected work in Debian. If you have problems with the deb package on another distro, try compiling the package according to the instructions in the README.
