### ISSUE TITLE
Resim Yapıştırma

### ISSUE THREAD

**Issue by ByEzel93** [eneshecan/whatsapp-for-linux#275]
Merhabalar hocam, öncelikle bu uygulamayı geliştirdiğiniz için teşekkür ederim.
Linux sistemler de bir resim'i kopyaladığınız da whatsapp uygulaması üzerinden mesaj gönderirken kopyalanan resimi yapıştır diyemiyoruz.

Aslında diyoruz fakat yapıştırmıyor :) konu ile alakalı bir güncelleme atarsanız çok memnun olurum.

Kullandığım sistem : Linux Mint LMDE 5

**Comment by eneshecan** [comment]
Selam @ByEzel93. #79 a bakabilirsin. WebKit bugı ve yapabileceğimiz çok bir şey yok.

**Comment by ByEzel93** [comment]
> Selam @ByEzel93. #79 a bakabilirsin. WebKit bugı ve yapabileceğimiz çok bir şey yok.

Tamamdır hocam teşekkür ederim
