### ISSUE TITLE
Paste image from Clipboard

### ISSUE THREAD

**Issue by saozer** [eneshecan/whatsapp-for-linux#277]
Sorry, i am new in this project and i am a beginer in C++. I would like to add the **possibility to paste images from the clipboard**. Is there anybody who can implement this feature?

**Comment by eneshecan** [comment]
Yeah well, it's an upstream issue as mentioned in #79 and I don't have any workarounds atm...

**Comment by saozer** [comment]
I think there is an event listener for Paste action. Here is my suggestion
according to my skill in other languages. As I told you last time, I can't
write any lines of C#, I am new. But Truly, there is a Clipboard object in
C#. try to understand the logic bellow

public void onPaste(TextBox){
    if (Clipboard.ContainsImage()){
           TextBox.addContent(Clipboard.getImage())
    }
}

**Comment by saozer** [comment]
> I find this as a deal breaker as well, would there be an option to include the paste images function?

Yes i think so. There is an Object with image Methods for clipboard
Clipboard.ContainsImage() // return True/false
Clipboard.getImage() // get image from clipboard
Clipboard.setImage() // put an image in the clipboard
