### ISSUE TITLE
Change Project Name

### ISSUE THREAD

**Issue by sabriunal** [eneshecan/whatsapp-for-linux#278]
Hi, Enes.

As you aware of you don't own Whatsapp brand name and it may couse legal problem to you.

Thanks for app.

Also Brodie brodcasted a video about Flathub Beta and talked about the app.

https://www.youtube.com/watch?v=UT1l-2bjcUg

**Comment by eneshecan** [comment]
Hi @sabriunal. Thank you for this but I have no intention to change the project name atm...

**Comment by Vistaus** [comment]
I don't know. On the one hand, the brand name is techically used. But on the other hand, it's not like it's a 3rd-party app or something: it's mostly a WhatsApp Web wrapper (no offense). So it's not like Meta can claim damages or something.
