### ISSUE TITLE
hitting the enter key does not send message but behaves like shift+enter

### ISSUE THREAD

**Issue by fu-zhou** [eneshecan/whatsapp-for-linux#285]
I did not find a way to turn off that hitting the enter key sends the message rather than doing a line break in the message currently being typed. I'd like to send the message only by klicking the send icon, hitting enter should behave like shift+enter now. Can that feature be implemented under configuration - chat like in the Android app?

**Comment by eneshecan** [comment]
I don't think that's possible atm since we don't have access to whatsapp's api...
