### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Aalexeey** [eneshecan/whatsapp-for-linux#298]
[ru.po.txt](https://github.com/eneshecan/whatsapp-for-linux/files/11642504/ru.po.txt)
https://disk.yandex.ru/d/jey6n_M3yraNjQ

**Comment by eneshecan** [comment]
I am not sure what is intended by this. Please read the contributing guidelines and explain what you wanted to achieve with your PR...

**Comment by eneshecan** [comment]
I can add you to our [translations project](https://poeditor.com/join/project/jMGkxVn3vN) which as an easy-to-use UI if you can provide an email address
