### ISSUE TITLE
Would it be possible to add a short "how to use this on the desktop"?

### ISSUE THREAD

**Issue by rubyFeedback** [eneshecan/whatsapp-for-linux#30]
Hey there,

My question is: could the main README be extended to a short "how to use this on the desktop"?

This may sound like a stupid question :) - however had, I have no smartphone/mobile, yet lots of
people nearby use whatsapp on their smartphone. So to me, it would really be useful to know how to use this, in order to then communicate with them if that is even possible (for example, right now I really don't know if it is possible or not; I read in the past that it is not possible so perhaps my knowledge is obsolete. Hope I could explain this strange issue request.)

Anyway please feel free to ignore this if it seems too much effort for too little gain. Thanks for reading!

**Comment by eneshecan** [comment]
Hello, thanks for your support! I really appreciate it :) Regarding your question; it's not possible to use whatsapp web without a mobile app installed on your mobile phone if I understand your question correctly. But of course, README can be extended to show how to install and use (step by step) on desktop.

**Comment by eneshecan** [comment]
Since installing different packages can be found easily according to their type and whatsapp web shows you how to connect on their initial page with a qr code, I am closing this issue.
