### ISSUE TITLE
Port to WebKit2GTK 4.1

### ISSUE THREAD

**Issue by hazel-bunny** [eneshecan/whatsapp-for-linux#302]
**Is your feature request related to a problem? Please describe.**
WebKit2GTK 4.0 is deprecated
https://discourse.gnome.org/t/webkit2gtk-4-1-added-to-gnome-sdk-webkit2gtk-4-0-deprecated/7053

**Describe the solution you'd like**
Port to WebKit2GTK 4.1, or when #239 is completed, WebKit2GTK 6.0

**Comment by eneshecan** [comment]
Switching to 4.1 is done in b7cbc5f but I kept the 4.0 reference in CMake in case 4.1 is not found.
