### ISSUE TITLE
Signal on the icon tray.

### ISSUE THREAD

**Issue by nipnipj** [eneshecan/whatsapp-for-linux#303]
I think this app needs a signal went there are unread new messages. Something like a red dot on the whatsapp icon.

**Comment by eneshecan** [comment]
We already have that implemented but we need to check if it's not working.

**Comment by nipnipj** [comment]
I see. Could anyone confirm whether it works on Linux mint 21? I haven't see it since I installed it.

**Comment by Aalexeey** [comment]
It works fine in Devuan.
