### ISSUE TITLE
Can't launch the appimage, webkit2gtk error.

### ISSUE THREAD

**Issue by nourserry** [eneshecan/whatsapp-for-linux#304]
**Description**
Just downloaded the latest release
When attempting to launch nothing shows up.
Terminal log:

(process:14149): Gtk-WARNING **: 09:06:09.239: Locale not supported by C library.
        Using the fallback 'C' locale.
<13>Jun 12 09:06:09 whatsapp-for-linux[14160]: 
<13>Jun 12 09:06:09 whatsapp-for-linux[14160]: ** (whatsapp-for-linux:14149): ERROR **: 09:06:09.929: Unable to spawn a new child process: Failed to spawn child process ?/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess? (No such file or directory)
zsh: trace trap (core dumped)  /home/[REDACTED]/Downloads/whatsapp-for-linux-1.6.3-x86_64.AppImage
`

**To Reproduce**
1. Download the latest release (1.6.3) appimage.
2. Launch
3. App crashes immediately

**Expected behavior**
App launches

**Screenshots**

**Environment**
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.3.5-2-MANJARO (64-bit)
Graphics Platform: Wayland

**Comment by eneshecan** [comment]
Hi, thanks for this! We already have that in #160 and need some help to fix it...
