### ISSUE TITLE
Color of selected text is not visible properly

### ISSUE THREAD

**Issue by namanchandak** [eneshecan/whatsapp-for-linux#307]
In the dark theme if we select text from a chat then the selected text color is not visible properly
![image](https://github.com/eneshecan/whatsapp-for-linux/assets/98888986/f1d5f962-aeb5-48fc-ab49-a5df2cfc84d6)

**Comment by namanchandak** [comment]
it should be like this

![image](https://github.com/eneshecan/whatsapp-for-linux/assets/98888986/396926d6-70a5-4535-a886-9bafb36fcb19)

**Comment by eneshecan** [comment]
Thanks for the issue @namanchandak! I think this is related to Webkit or Whatsapp web and there is nothing we can do about it except a dirty workaround...
