### ISSUE TITLE
App Lock Feature

### ISSUE THREAD

**Issue by PythonPlumber** [eneshecan/whatsapp-for-linux#310]
**Can you add some new Features**

1. Mute Audio, Disable Notifications
2. App Lock feature

**Comment by eneshecan** [comment]
First one is already there but we can implement the second.

**Comment by antidoid** [comment]
A nice touch with the app lock feature would to hide the details/contents of the message, so when you get a new message you see something like 

**WhatsApp**
**1 new message**

**Comment by deltalejo** [comment]
+1 For the lock feature.

**Comment by eneshecan** [comment]
There is now a built-in app lock feature on the privacy settings of WhatsApp web. So, I am closing this.
