### ISSUE TITLE
Open the app in-window if a tray process already exists

### ISSUE THREAD

**Issue by FelixFourcolor** [eneshecan/whatsapp-for-linux#323]
Continued from #320.

Thank you for fixing the first part of my earlier issue. I create another issue for the second part as requested.

Current behavior: When the app is closed to tray, in order to reopen the app, you have click the tray icon > show. Opening the app from the system menu would do nothing.

Suggestion: When the app is launched, if an instance is already running in tray, open it *in-window* regardless of the "start in tray" preference; only if not, start a new process and open it in-window or in-tray depending on the "start in tray" preference.

This will particularly benefit Gnome users, because vanilla Gnome does not have tray icons. But I think everyone can benefit from the convenience of being able to launch the app from both the tray icon and the system menu.

**Comment by FelixFourcolor** [comment]
Appendum: In case you question why a vanilla Gnome user would want to turn on "start in tray", it is very useful to combine it with "autostart".

**Comment by eneshecan** [comment]
This should also be fixed now and it works for me. Could you check the latest main and see if it works before we release it?

Thanks again :)
