### ISSUE TITLE
Appimage loads blank screen

### ISSUE THREAD

**Issue by JonnyTech** [eneshecan/whatsapp-for-linux#326]
**Description**
When starting the AppImage there is nothing shown in the application window

**To Reproduce**
`$ ./whatsapp-for-linux-1.6.4-x86_64.AppImage `
No terminal message
Blank screen as shown below

**Expected behavior**
App to display content instedl of a blank empty window

**Screenshots**
![image](https://github.com/eneshecan/whatsapp-for-linux/assets/3584732/2ef6edbb-2832-4f2f-ac0e-2bde0a18a23c)

**Environment**
Distro: Debian 11 based MX Linux 21
Package: whatsapp-for-linux-1.6.4-x86_64.AppImage
Desktop Environment or Window Manager: Xfce 4.18

**Comment by eneshecan** [comment]
Unfortunately, we have a problem of bundling webkit to appimage as mentioned here #160. Any help is appreciated to fix this.

**Comment by francogrex** [comment]
Unfortunately there are a LOT of bugs and issues. One wonders whether it is useful to even pursue development of a project like this one with that many issue, I think it should be abandoned.

**Comment by eneshecan** [comment]
> Unfortunately there are a LOT of bugs and issues. One wonders whether it is useful to even pursue development of a project like this one with that many issue, I think it should be abandoned.

I am trying to fix them when I find the time. Contributions are always welcome though.
