### ISSUE TITLE
System tray icon is needed show as whatsapp icon

### ISSUE THREAD

**Issue by hurelhuyag** [eneshecan/whatsapp-for-linux#329]
**Description**
Looks like the Whatsapp icon in the system tray is implemented. But I'm seeing a 3 dots icon on my system tray.

**To Reproduce**
1. Fresh install from Ubuntu 23.04 software store 
2. Open the app
3. Open Preferences
4. Check Star in Tray and Close to Tray checkmarks
5. The tray icon appears as 3 dots.

**Expected behavior**
WhatsApp logo appear in the system tray

**Screenshots**
![Screenshot from 2023-08-17 10-53-07](https://github.com/eneshecan/whatsapp-for-linux/assets/1059242/72c62d04-4847-4be6-9386-e9b999f2f75e)

**Environment**
 - Distro: Ubuntu 23.04 amd64
 - Package: snap
 - Desktop Environment or Window Manager: Gnome

**Comment by Martzy303** [comment]
For me the icon is a black mail envelope.

**Comment by eneshecan** [comment]
Please see #98
