### ISSUE TITLE
Support for pasting images?

### ISSUE THREAD

**Issue by elsopapa** [eneshecan/whatsapp-for-linux#33]
support for paste images from clipboard

**Comment by eneshecan** [comment]
Thank you for this. I'll check if it's possible.

**Comment by eneshecan** [comment]
I just checked this and found out that it works! Could you please confirm?

**Comment by elsopapa** [comment]
it  doesnt work for me, im using the snap version.

**Comment by elsopapa** [comment]
doesnt work with last .deb either. Im using xubuntu 20

**Comment by eneshecan** [comment]
Interesting, works on Ubuntu 20.04. Would be nice to get feedback from other distros as well.

**Comment by elsopapa** [comment]
doesnt work in linux mint

**Comment by elsopapa** [comment]
Linux Mint 19.3 with  deb package.

**Comment by juxuanu** [comment]
Works on ArchLinux with LTS kernel and Gnome 3.36.4

**Comment by elsopapa** [comment]
Maybe its the desktop and not the distro? it didnt work un xfce on debian 10 or xubuntu 20 , and mate on mint 19.

**Comment by elsopapa** [comment]
can i help with some debug? tell me how.

**Comment by eneshecan** [comment]
@elsopapa Currently I have no information why it works on gnome but not other DEs. It would worth to investigate webkit2 or gtk so that if we need to do something explicitly.

**Comment by eneshecan** [comment]
Can you try after installing xfce4-clipman on xfce? Maybe some tweaks have to be done for some DEs...

**Comment by elsopapa** [comment]
it doesnt work with  xfce4-clipman :(

**Comment by eneshecan** [comment]
I'll debug the application for this once I have time.

**Comment by eneshecan** [comment]
I recently created an aur package. It worked maybe because of some plugins added as dependencies. Could anyone check if this works on arch?

**Comment by bonanza123** [comment]
> I recently created an aur package. It worked maybe because of some plugins added as dependencies. Could anyone check if this works on arch?

which aur package do you mean?
This one? https://aur.archlinux.org/packages/whatsapp-for-linux
With this one it does not work for me.

**Comment by eneshecan** [comment]
@bonanza123 Can I ask which desktop environment and file manager are you using? Also how are you copying the file to clipboard just for me to understand it better. Because I am either using Ctrl+C or Copy Location.

**Comment by bonanza123** [comment]
> @bonanza123 Can I ask which desktop environment and file manager are you using? Also how are you copying the file to clipboard just for me to understand it better. Because I am either using Ctrl+C or Copy Location.

Sorry for the late reply. I am using Archlinux with KDE.
I tried the following: 
- open spectacle app
- create a screenshot + hit copy to clipboard
- try CTRL + V or right-click -> paste

**Comment by eneshecan** [comment]
Thank you @bonanza123. Could you debug the application to see if you get any messages from webkit or gtk while pasting?

**Comment by bonanza123** [comment]
> Thank you @bonanza123. Could you debug the application to see if you get any messages from webkit or gtk while pasting?

sure, how do I do that?

**Comment by eneshecan** [comment]
See [Build & Run](https://github.com/eneshecan/whatsapp-for-linux#build--run) please.

**Comment by kawaK1320** [comment]
> Works on ArchLinux with LTS kernel and Gnome 3.36.4

not working for me, arch on lts also! kde plasma as DE!

**Comment by gahara31** [comment]
it also doesn't work on manjaro-cinnamon-nemo, I'm using kernel 5.8.16-2

**Comment by emmegamma** [comment]
I did test it myself on Ubuntu 20.04 (default Gnome). It does NOT work for me, neither in the snap nor in the deb package version.
The issue seems to be not DE-related but elsewhere.. 
I can try debugging when I have time, if that helps

**Comment by aDogCalledSpot** [comment]
On Arch Linux with awesome as WM. Doesn't work and I'm not getting anything on stdout when using the normal Debug.

**Comment by eneshecan** [comment]
@aDogCalledSpot Thanks! Could you tell me how do you copy image? Copy Location, Copy, etc?

**Comment by aDogCalledSpot** [comment]
I copied an image to my normal clipboard (in Firefox, right-click the image -> "Copy Image"). I attempted to use Ctrl-V and Right-click -> Paste in WhatsApp which both had no effect.

**Comment by eneshecan** [comment]
Well, it only works with images which are saved on your machine. i.e. try copying an image from your file manager.

**Comment by aDogCalledSpot** [comment]
My apologies, I wasn't aware of that. Copying a local file with the "Copy" option in Dolphin does work.

**Comment by eneshecan** [comment]
No problem at all. I just wonder if everyone having that problem tries to do that. If so, we can close this issue.

**Comment by eneshecan** [comment]
I will close this soon due to inactivity and probable incorrect usage of the functionality.
