### ISSUE TITLE
Blank screen after leaving in background or in tray

### ISSUE THREAD

**Issue by Martzy303** [eneshecan/whatsapp-for-linux#330]
**Description**
After minimizing or in tray or even leaving in in the background of another window, it's blank screen, to make it work again I need to push the refresh button.
What I noticed is that if I have whatsapp on my right half screen let's say, but I have focus on the window on the right side, I can see the new messages, if any, but as soon as I click on the window to reply, it goes white.

**To Reproduce**
1. Open Whatsapp
2. Minimize in bar or tray or not focus it and wait for a while 
3. Open it again

**Expected behavior**
To work fine as before

**Screenshots**
https://i.imgur.com/NyHbYAg.png

**Environment**
 - Distro [Linux Mint 21.2]
 - Package [snap]
 - Desktop Environment or Window Manager [Cinnamon]

And this is the log, last line is after 40 mins when I pressed Preferences

```
~$ whatsapp-for-linux
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/boot /boot none bind,ro 0 0): permission denied
Gtk-Message: 13:00:28.161: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:00:28.161: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: 
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: ** (whatsapp-for-linux:829355): WARNING **: 13:00:28.252: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: 
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: ** (whatsapp-for-linux:829355): WARNING **: 13:00:28.252: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: SettingMap: Key file does not have key “min-font-size” in group “web”, returning default value: 0
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: SettingMap: Key file does not have key “zoom-level” in group “general”, returning default value: 1
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: Gtk-Message: 13:00:28.292: Failed to load module "xapp-gtk3-module"
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: Gtk-Message: 13:00:28.292: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: SettingMap: Key file does not have key “header-bar” in group “general”, returning default value: 1
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: 
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: ** (WebKitWebProcess:829469): WARNING **: 13:00:28.538: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: 
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: ** (WebKitWebProcess:829469): WARNING **: 13:00:28.538: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: 
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: ** (WebKitWebProcess:829469): WARNING **: 13:00:28.575: Failed to get atspi registered event listeners: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.468" (uid=1000 pid=829469 comm="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWeb" label="snap.whatsapp-for-linux.whatsapp-for-linux (enforce)") interface="org.a11y.atspi.Registry" member="GetRegisteredEvents" error name="(unset)" requested_reply="0" destination=":1.1" (uid=1000 pid=2071 comm="/usr/libexec/at-spi2-registryd --use-gnome-session" label="unconfined")
<13>Aug 18 13:00:28 whatsapp-for-linux[829461]: 
<13>Aug 18 13:00:46 whatsapp-for-linux[829461]: Cannot connect to server socket err = No such file or directory
<13>Aug 18 13:00:46 whatsapp-for-linux[829461]: Cannot connect to server request channel
<13>Aug 18 13:00:46 whatsapp-for-linux[829461]: jack server is not running or cannot be started
<13>Aug 18 13:00:46 whatsapp-for-linux[829461]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<13>Aug 18 13:00:46 whatsapp-for-linux[829461]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<13>Aug 18 13:00:46 whatsapp-for-linux[829461]: Cannot connect to server socket err = No such file or directory
<13>Aug 18 13:00:46 whatsapp-for-linux[829461]: Cannot connect to server request channel
<13>Aug 18 13:00:46 whatsapp-for-linux[829461]: jack server is not running or cannot be started
<13>Aug 18 13:00:46 whatsapp-for-linux[829461]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<13>Aug 18 13:00:46 whatsapp-for-linux[829461]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<13>Aug 18 13:40:21 whatsapp-for-linux[829461]: SettingMap: Key file does not have key “min-font-size” in group “web”, returning default value: 0

```
And this is when I pressed refresh icon, if it matters

```
<13>Aug 18 13:42:03 whatsapp-for-linux[829461]: Gtk-Message: 13:42:03.217: Failed to load module "xapp-gtk3-module"
<13>Aug 18 13:42:03 whatsapp-for-linux[829461]: Gtk-Message: 13:42:03.218: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
<13>Aug 18 13:42:03 whatsapp-for-linux[829461]: 
<13>Aug 18 13:42:03 whatsapp-for-linux[829461]: ** (WebKitWebProcess:834329): WARNING **: 13:42:03.434: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied
<13>Aug 18 13:42:03 whatsapp-for-linux[829461]: 
<13>Aug 18 13:42:03 whatsapp-for-linux[829461]: ** (WebKitWebProcess:834329): WARNING **: 13:42:03.434: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
<13>Aug 18 13:42:03 whatsapp-for-linux[829461]: 
<13>Aug 18 13:42:03 whatsapp-for-linux[829461]: ** (WebKitWebProcess:834329): WARNING **: 13:42:03.436: Failed to get atspi registered event listeners: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.474" (uid=1000 pid=834329 comm="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWeb" label="snap.whatsapp-for-linux.whatsapp-for-linux (enforce)") interface="org.a11y.atspi.Registry" member="GetRegisteredEvents" error name="(unset)" requested_reply="0" destination=":1.1" (uid=1000 pid=2071 comm="/usr/libexec/at-spi2-registryd --use-gnome-session" label="unconfined")
<13>Aug 18 13:42:03 whatsapp-for-linux[829461]: 
<13>Aug 18 13:42:16 whatsapp-for-linux[829461]: Cannot connect to server socket err = No such file or directory
<13>Aug 18 13:42:16 whatsapp-for-linux[829461]: Cannot connect to server request channel
<13>Aug 18 13:42:16 whatsapp-for-linux[829461]: jack server is not running or cannot be started
<13>Aug 18 13:42:16 whatsapp-for-linux[829461]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<13>Aug 18 13:42:16 whatsapp-for-linux[829461]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<13>Aug 18 13:42:16 whatsapp-for-linux[829461]: Cannot connect to server socket err = No such file or directory
<13>Aug 18 13:42:16 whatsapp-for-linux[829461]: Cannot connect to server request channel
<13>Aug 18 13:42:16 whatsapp-for-linux[829461]: jack server is not running or cannot be started
<13>Aug 18 13:42:16 whatsapp-for-linux[829461]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<13>Aug 18 13:42:16 whatsapp-for-linux[829461]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
```

**Comment by Martzy303** [comment]
Seems like the problem is only on the Snap package, the Flatpak works just fine

**Comment by mshs013** [comment]
It goes blank also in debian 12 flatpak package.

**Comment by i-am-ecc** [comment]
It happens with the amd64 .deb package as well

**Comment by Martzy303** [comment]
It happened just once today on the Flatpak, at least is not like the Snap package, there if I lost focus of the window it happened every time.

**Comment by i-am-ecc** [comment]
I tried the downgrade from 1.6.4 to 1.6.3, but the problem still persists.

**Comment by Martzy303** [comment]
I thought the Flatpak is better, but seems it's the same.
It is fine if you don't receive messages, but when you receive a new message and go back to the window, it's blank.

**Comment by PATRONzzz** [comment]
The same is Flatpack. It started on version 1.6.0, after upgrading to version 1.6.3, the error remained.

**Comment by Martzy303** [comment]
> The same is Flatpack. It started on version 1.6.0, after upgrading to version 1.6.3, the error remained.

So if I install the Flatpack 1.6.0 all works fine?

**Comment by Martzy303** [comment]
I'm wondering if it's from the WhatsApp or from the app.
Let's hope @eneshecan will shed some light on it.

**Comment by eneshecan** [comment]
Interesting issue. It could be either on WhatsApp or webkit side. However, I don't have any time these days as I am on vacation...

**Comment by Martzy303** [comment]
> Interesting issue. It could be either on WhatsApp web or webkit side. However, I don't have any time these days as I am on vacation...
Have fun on your holiday!
I will revert to using the browser version until this one is back in business.

**Comment by facundoo** [comment]
I have same problem.
Ubuntu 22.04 - WA 1.6.4 - Chrome 115.0.5790.102 (Build oficial) (64 bits) - Firefox 116.0.3 (64 bits)

**Comment by Dwahgon** [comment]
At least for me, it's possible to workaround this issue by simply clicking the reload button on the top left
![image](https://github.com/eneshecan/whatsapp-for-linux/assets/47753585/cefc8afa-38ce-4d7b-8e9c-15b73480619c)

**Comment by Martzy303** [comment]
> At least for me, it's possible to workaround this issue by clicking the reload button on the top left ![image](https://user-images.githubusercontent.com/47753585/264041982-cefc8afa-38ce-4d7b-8e9c-15b73480619c.png)

@Dwahgon For me it's not, takes too much time to refresh, if I have a conversation it takes ~20s to respond for each message, not fine when you work, maybe for friends, but not for work.

**Comment by wcota** [comment]
Same problem here using the `whatsapp-for-linux` AUR package

**Comment by nipnipj** [comment]
Same. Linux mint 21.2 here. Usually when in background and a message is received.

**Comment by zafhiel** [comment]
Guys, I can confirm that on Manjaro the issue gets temporarily fixed by clicking the update button. However, the problem reoccurs every time the app loses focus. Honestly, in its current state, this app is pretty much unusable. I've been using `scrcpy` as an alternative, but it's not the same. I really like this app, but if it continues to have these issues, I'll sadly have to stop using it.

**Comment by Martzy303** [comment]
I'm using the web version until it gets fixed, for me the refresh button it's not good enough, I use it just for work and I can't have pauses between messages of 30 seconds, that's how much it takes to refresh.
If it was just for friends and family it was not that big of a deal.
Maybe eneshecan will get it fixed soon, when he comes from holiday.

**Comment by fridrich** [comment]
> Interesting issue. It could be either on WhatsApp web or webkit side. However, I don't have any time these days as I am on vacation...

Still on vacation?

**Comment by eneshecan** [comment]
I've got an `Update WhatsApp` notification today. After updating it, didn't see the problem so far.

**Comment by Switch123456789** [comment]
I am on `arch (gnome 44)` and I have the same issue but even if I click the refresh the window remains blank.

**Comment by nipnipj** [comment]
The issues persist for me.

**Comment by dCo3lh0** [comment]
Since i thought the problem was the same related to last NewsFlash RSS Reader issue with webkit, that i had this week, i thought the solution using the environment variable command that solved there maybe would work in whatsapp flatpak as well, i just tried and worked, so here is the solution, go to flatseal, select whatsapp for linux and on the right menu in the "Environment" category, add this exactly Environment Variable for it to work:

`WEBKIT_DISABLE_DMABUF_RENDERER=1`

now close flatseal and start whatsapp for linux again, it will work without a single doubt, so hope my tip helps you guys.

**Comment by dCo3lh0** [comment]
On AppImage maybe it would work if you add the environment variable to the AppRun Script

**Comment by Switch123456789** [comment]
According to [this projects readme](https://github.com/pot-app/pot-desktop), the latest version of [Webkit2Gtk]() has issues with proprietary NVIDIA-drivers. Quote:

"Because the Nvidia proprietary driver does not fully implement DMABUF, it will cause failure to start and crash. Please downgrade or add environment variables to turn off the use of DMABUF `/etc/environment` (or other places where environment variables are set) `WEBKIT_DISABLE_DMABUF_RENDERER=1`"

**Comment by ndias** [comment]
In my case the WEBKIT_DISABLE_DMABUF_RENDERER=1 doesn't solve the problem, I'm running from the terminal like this
export WEBKIT_DISABLE_DMABUF_RENDERER=1; whatsapp-for-linux

**Comment by Switch123456789** [comment]
@ndias Did you also try what I did?

**Comment by ndias** [comment]
> @ndias Did you also try what I did?

No, but I think it's the same when you put something in /etc/environment it will be set for all users, what I done was set only for my user.

**Comment by Switch123456789** [comment]
It would make sense to me that you have to reload your shell or the gpu-drivers or something. I don't think a changed variable gets applied to an already active service or driver but that's not my expertise. All I can say is: after a restart it worked for me. :man_shrugging: but you do you.

**Comment by Martzy303** [comment]
> EDIT: I added `WEBKIT_DISABLE_DMABUF_RENDERER=1` to `/etc/environment` and after a restart wal is working fine again.

Have tried this, I can receive new messages but after a while goes back to blank screen. Also, if I use the refresh button I get logged out and it asks to pair again, this did not happen before.

**Comment by AndreasBackx** [comment]
> "Because the Nvidia proprietary driver does not fully implement DMABUF, it will cause failure to start and crash. Please downgrade or add environment variables to turn off the use of DMABUF `/etc/environment` (or other places where environment variables are set) `WEBKIT_DISABLE_DMABUF_RENDERER=1`"

Having not yet tried your workaround, I do want to mention that I experience this issue on 3 different machines. 2 of which are running on AMD (RX 6800 and U4750) and one is running on Nvidia (RTX 2070 Super afaik) so if the workaround works, it's not an issue limited to Nvidia.

**Comment by ndias** [comment]
> It would make sense to me that you have to reload your shell or the gpu-drivers or something. I don't think a changed variable get applied to an already active service or driver but that's not my expertise. All I can say is: after a restart it worked for me. But you do you.

No, I think the nvidia driver will not care about environment variables, I think this variable is for webkit, that's the reason I run the variable in my local user, and like  @AndreasBackx wrote, I think this is not a problem of nvidia, I have the problem in a machine with a nvidia GPU and the same problem in a machine with an Intel GPU

**Comment by drujd** [comment]
This has nothing to do with Nvidia. I am experiencing this with AMD GPU (running amdgpu driver).

**Comment by drujd** [comment]
I think that at least in my case, this is caused by notifications popping up... Disabled notifications and so far no freeze.

**Comment by dCo3lh0** [comment]
have you guys updated the dependencies in flatpak for whatsapp for linux?
org.freedesktop.Platform.GL.nvidia-535-104-12
org.freedesktop.Platform.GL32.nvidia-535-104-12

in terminal:
`flatpak install org.freedesktop.Platform.GL.nvidia-535-104-12 org.freedesktop.Platform.GL32.nvidia-535-104-12`

now remove the old one (in my case it was 535-104-05):
`flatpak remove flatpak install org.freedesktop.Platform.GL.nvidia-535-104-05 org.freedesktop.Platform.GL32.nvidia-535-104-05`

**Comment by Martzy303** [comment]
I had  nvidia 525, changed to 535 now. Have also installed the dependencies 535-104-12, but I can't remove the old ones.

Have tried to run ` flatpak remove flatpak install org.freedesktop.Platform.GL.nvidia-535-104-05 org.freedesktop.Platform.GL32.nvidia-535-104-05` 

And I get `Warning: flatpak is not installed
Warning: install is not installed
Found installed ref ‘runtime/org.freedesktop.Platform.GL.nvidia-535-104-12/x86_64/1.4’ (system). Is this correct? [Y/n]:`

Yet in the Update Manager I can see an update for it

https://i.imgur.com/indxKgK.png

**Comment by Martzy303** [comment]
Have tried disabling notifications and it seems to be working.

I'm using 535.104.05, also it sais in the Driver Manager also, just checked now, there is no option for 535-104-12.
For you notifications work with 535-104-12?

```
:~$ nvidia-smi
Wed Sep 27 20:41:55 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    Off | 00000000:01:00.0  On |                  N/A |
| N/A   42C    P0              22W /  80W |    138MiB /  6144MiB |     36%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1369      G   /usr/lib/xorg/Xorg                          133MiB |
+---------------------------------------------------------------------------------------+
:~$ flatpak uninstall --unused

These runtimes in installation 'system' are pinned and won't be removed; see flatpak-pin(1):
  runtime/org.freedesktop.Platform.GL.nvidia-535-104-12/x86_64/1.4
  runtime/org.freedesktop.Platform.GL32.nvidia-535-104-12/x86_64/1.4
  runtime/org.gtk.Gtk3theme.Mint-Y-Dark-Blue/x86_64/3.22
Nothing unused to uninstall

```

**Comment by dCo3lh0** [comment]
Im using LMDE 5 in the moment, in a few days will update to LMDE 6 based on Debian 12, and i do use the official repository of drivers from Nvidia (only available till debian 11) which in the moment is on 535.104.12, i do use a RTX 2060 GPU. Anyways, see if you dont have any further update for your drivers, if there isn't any newer them dont install the version 104.12 i've installed, install the 535.104.05 which is for your current nvidia driver, it needs to be the exact same version so:

uninstall:
`flatpak remove org.freedesktop.Platform.GL.nvidia-535-104-12 org.freedesktop.Platform.GL32.nvidia-535-104-12`

install:
`flatpak install org.freedesktop.Platform.GL.nvidia-535-104-05 org.freedesktop.Platform.GL32.nvidia-535-104-05`

thats the end for me here, hope it helps you now.

**Comment by the-solipsist** [comment]
I'm having the same issue. I just wanted to add that the dmesg error I'm getting is:

```
[Thu Sep 28 05:36:33 2023] WebKitWebProces[105317]: segfault at 4 ip 00007f9c227b35cf sp 00007ffc8ca17fe0 error 4 in libwebkit2gtk-4.0.so.37.67.3[7f9c22316000+2d8b000] likely on CPU 3 (core 3, socket 0)
[Thu Sep 28 05:36:33 2023] Code: 5c 41 5d 41 5e 41 5f 5d c3 e8 6d d9 8e 02 cc cc cc cc cc cc cc cc cc cc cc cc cc 41 57 41 56 41 55 41 54 53 49 89 f6 48 89 fb <4c> 8b 7e 04 48 8b 46 20 4c 8b 60 10 4d 89 fd
 49 c1 ed 20 31 ff 44
```

This is what it says when I start it from the terminal:
```
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: ** (whatsapp-for-linux:20958): WARNING **: 14:07:17.531: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: ** (whatsapp-for-linux:20958): WARNING 
**: 14:07:17.531: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: ** (whatsapp-for-linux:20958): WARNING **: 14:07:17.532: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: ** (whatsapp-for-linux:20958): WARNING **: 14:07:17.532: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “min-font-size” in group “web”, returning default value: 0
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “close-to-tray” in group “general”, returning default value: 0
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “start-in-tray” in group “general”, returning default value: 0
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “start-minimized” in group “general”, returning default value: 0
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: SettingMap: Key file does not have group “appearance”, returning default value: 0
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: 
<13>Sep 27 14:07:17 whatsapp-for-linux[20964]: (whatsapp-for-linux:20958): Gtk-CRITICAL **: 14:07:17.745: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
<13>Sep 27 14:18:01 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “start-in-tray” in group “general”, returning default value: 0
<13>Sep 27 14:18:01 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “start-minimized” in group “general”, returning default value: 0
<13>Sep 27 14:18:01 whatsapp-for-linux[20964]: SettingMap: Key file does not have group “appearance”, returning default value: 0
<13>Sep 27 14:18:01 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “min-font-size” in group “web”, returning default value: 0
<13>Sep 27 16:11:33 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “start-in-tray” in group “general”, returning default value: 0
<13>Sep 27 16:11:33 whatsapp-for-linux[20964]: SettingMap: Key file does not have key “start-minimized” in group “general”, returning default value: 0
<13>Sep 27 16:11:33 whatsapp-for-linux[20964]: SettingMap: Key file does not have group “appearance”, returning default value: 0
```

**Comment by Martzy303** [comment]
For me it works fine with notifications disabled, it's not ideal, but at least it is working.
Until it properly gets fixed, I'll keep an eye on my phone for notifications and reply on the PC.

**Comment by dCo3lh0** [comment]
@the-solipsist maybe missing libaspell libnuspell and libvoikko libs? dont know which distro you use, but search in your package manager for those libs, install it and try running again.

**Comment by the-solipsist** [comment]
> @the-solipsist maybe missing libaspell libnuspell libhspell and libvoikko libs? 

All four of those are for spelling / grammar features. They shouldn't have any impact at all on screen rendering.

**Comment by Martzy303** [comment]
@dCo3lh0 I got an update to 535-113-01, did `flatpak install org.freedesktop.Platform.GL.nvidia-535-111-01 org.freedesktop.Platform.GL32.nvidia-535-113-01` and ` flatpak remove flatpak install org.freedesktop.Platform.GL.nvidia-535-104-05 org.freedesktop.Platform.GL32.nvidia-535-104-05`

When  I run `flatpak uninstall --unused`
```
These runtimes in installation 'system' are pinned and won't be removed; see flatpak-pin(1):
  runtime/org.freedesktop.Platform.GL.nvidia-535-113-01/x86_64/1.4
  runtime/org.freedesktop.Platform.GL32.nvidia-535-113-01/x86_64/1.4
  runtime/org.gtk.Gtk3theme.Mint-Y-Dark-Blue/x86_64/3.22
Nothing unused to uninstall

```
Does this mean they are not used, if they show here? Do they need to be activated or something?

// Have activated notifications again to see if it got fixed.

**Comment by codevski** [comment]
> In my case the WEBKIT_DISABLE_DMABUF_RENDERER=1 doesn't solve the problem, I'm running from the terminal like this export WEBKIT_DISABLE_DMABUF_RENDERER=1; whatsapp-for-linux

This worked for me...I guess a temp solution for now

**Comment by kmorkah** [comment]
temporarily, I turn off the desktop alram, It would be Okay until next version.

Environment

Distro [PopOS 22.04 LTS ]
Package [snap]
Desktop Environment or Window Manager [gnome 3.0]

**Comment by marracuene** [comment]
Also getting this in last few months, after a long while of stable usage.

Distro: `Linux Mint 20.3`
Kernel: `5.4.0-162-generic`
Package: `snap`
Version: `1.6.4`
Desktop Environment or Window Manager: `Cinnamon`
Webkit: `libwebkit2gtk-4.0-37:amd64                 2.38.6-0ubuntu0.20.04.1`

Tried the following workarounds without success:
 - disabling notifications via hamburger menu > Preferences
 - WEBKIT_DISABLE_DMABUF_RENDERER=1

Then I tried the below and it seems to be working so far (6h and counting, and I have suspended and rewoken the laptop without any grey screens):
 - disabling notifications via Whatsapp Web menu > Settings > notifications

**Comment by kmorkah** [comment]
> Also getting this in last few months, after a long while of stable usage.
> 
> Distro: `Linux Mint 20.3` Kernel: `5.4.0-162-generic` Package: `snap` Version: `1.6.4` Desktop Environment or Window Manager: `Cinnamon` Webkit: `libwebkit2gtk-4.0-37:amd64 2.38.6-0ubuntu0.20.04.1`
> 
> Tried the following workarounds without success:
> 
> * disabling notifications via hamburger menu > Preferences
> * WEBKIT_DISABLE_DMABUF_RENDERER=1
> 
> Then I tried the below and it seems to be working so far (6h and counting, and I have suspended and rewoken the laptop without any grey screens):
> 
> * disabling notifications via Whatsapp Web menu > Settings > notifications

I set it up, but the results are still the same.

Distro: Pop!OS 22.04 LTS
Kernel: 6.5.6-76060506-generic
Laptop :  Lenovo ThinkPad P14s Gen 2a
Process :  AMD® Ryzen 7 pro 5850u with radeon graphics × 16

**Comment by anishjp** [comment]
Even the one available in Copr repo (https://copr.fedorainfracloud.org/coprs/nunodias/whatsapp-for-linux/) also has the same problem.

**Comment by deltalejo** [comment]
I was experiencing this issue until today, when a notification appeared on the app to update Whatsapp, and after doing the update I haven't experienced the issue so far.

**Comment by abclution** [comment]
Setting hardware acceleration to "never" (boo) fixes this it seems.


![image](https://github.com/eneshecan/whatsapp-for-linux/assets/10130237/05564d55-682a-4a97-b98b-4575e14d1553)

**Comment by Martzy303** [comment]
Seems to be working now, I get the notifications in the list, but I don't see the preview like the other notifications, yet I have everything checked in settings.

https://i.imgur.com/DDlv2oJ.png

**Comment by Martzy303** [comment]
Fixed
