### ISSUE TITLE
Frozen interface followed by reset

### ISSUE THREAD

**Issue by wpwpwpwpw** [eneshecan/whatsapp-for-linux#334]
**Description**
After a while of starting the app, all its interface but the top toolbar freezes, and clicking "Refresh" is needed in order to keep using it. The app is unusable because the next time I want to send a message, I always need to refresh the app. Seems like the "web" component of the app just stops working. The notifications also stop working.

**Environment**
 - Manjaro
 - AUR
 - Cinnamon
 - Whatsapp for Linux 1.6.4

**Comment by nipnipj** [comment]
Same. Linux min 21.2 here.

**Comment by eneshecan** [comment]
It's probably related to webkit. However, changing Hardware Acceleration to `On Demand` in Preferences could solve it.

**Comment by wpwpwpwpw** [comment]
Thank you for the response. However, after testing, the problem persists, either with `On Demand` or `Never` selected in Hardware Acceleration.

**Comment by wpwpwpwpw** [comment]
I've been trying to let it in `On demand` mode and I started having the problem reported by another issue thread, the #336.

**Comment by eneshecan** [comment]
See #330 please
