### ISSUE TITLE
WebKitWebProcess keeps crashing

### ISSUE THREAD

**Issue by winkelnp** [eneshecan/whatsapp-for-linux#340]
**Description**
When waking WhatsappForLinux from the status bar (sometimes even from a minimised window) the window is unreactive until the page is reloaded and the system gets an application crash from WebKitWebProcess.

Error message name is "WebKitWebProcess killed by SIGSEGV"

**To Reproduce**
1. Set WhatsApp-For-Linux to close to tray
2. Close active window
3. Return to it a bit later
4. See the error

**Expected behavior**
Whatsapp page is shown

**Screenshots**
page has to be reloaded to be able to interact

**Environment**
 - Distro: Fedora 38
 - Package: Flathub with version 1.6.3
 - Desktop Environment: GNOME 44.5 on Wayland

**Comment by eneshecan** [comment]
Could be the same as #330.

**Comment by winkelnp** [comment]
Ah yes, sorry I missed that, that should be the same thing

**Comment by Switch123456789** [comment]
Take a look at [this](https://github.com/eneshecan/whatsapp-for-linux/issues/330#issuecomment-1734885601)!

**Comment by GamzeeRakoon** [comment]
can confirm have the same issue been having it for weeks and no logs get made in the terminal and none in gnomes error centre
![image](https://github.com/eneshecan/whatsapp-for-linux/assets/41258148/b295408c-afad-4384-827a-9a8c6e8040b4)
![image](https://github.com/eneshecan/whatsapp-for-linux/assets/41258148/d4839658-e116-4d66-8844-a1354d8ef678)
