### ISSUE TITLE
Return from background with .desktop file

### ISSUE THREAD

**Issue by winkelnp** [eneshecan/whatsapp-for-linux#341]
**Is your feature request related to a problem? Please describe.**
Often, when I have WhatsApp closed to my system tray and I need to open it again, I will (vaguely) automatically try to open it throught the application list and clicking on the app there instead of going through the status bar and clicking "open", it is quite frustrating then that it opens another instance (to the status bar) instead of opening the existing one.

**Describe the solution you'd like**
Calling the program checks whether there is another running and if it is, opens that. Current operation could be a commandline option? (or if this functionality were a commandline tag, that'd also work fine for me)

**Comment by eneshecan** [comment]
This is already in 1.6.4 but I didn't have time to update flatpak yet. Will do it now...

**Comment by iacobucci** [comment]
> This is already in 1.6.4 but I didn't have time to update flatpak yet. Will do it now...

How would this be accompilshed? Sadly with simply `wasistlos` it doesnt work to me :(

**Comment by 0yqc** [comment]
I would like to open this again, as it is fixed for not opening another instance. But if you run the .desktop file, nothing happens. Instead I'd like to see the currently open instance showing up again.
