### ISSUE TITLE
Screen stays blank on GNOME 45.0

### ISSUE THREAD

**Issue by jubalh** [eneshecan/whatsapp-for-linux#342]
I upgraded my system (openSUSE Tumbleweed, rolling release) and after whatsapp-for-linux only started a blank screen.

I'm not sure why yet. This upgrade got me the new GNOME 45.0, which might be related.
Here some other versions:

webkit2gtk4 2.42.0
gtkmm3 3.24.8

**To Reproduce**
1. Run latest openSUSE Tumbleweed
2. Start the app

**Expected behavior**
See messages.

**Screenshots**
![wfl](https://github.com/eneshecan/whatsapp-for-linux/assets/1658215/8c7500d1-6d7a-493c-b85f-654db2db8752)

**Environment**
 - Distro: openSUSE Tumblweed snapshot 20230921
 - Package: Distro package 1.6.4  (I'm the maintainer)
 - Desktop Environment or Window Manager: Gnome 45.0

**Comment by eneshecan** [comment]
Please see #330

**Comment by jubalh** [comment]
I actually searched through open issues. And found 330.
But the `after leaving in background or in tray` made me decide that it might be another cause and so I opened a new bug.

**Comment by eneshecan** [comment]
Sorry, I didn't mean to imply that you didn't look into issues. It is true that your issue description fits the actual problem better. So, we can keep this :)

**Comment by Pryka** [comment]
It's a different issue, I have the same problem after flatpak runtime update to gnome 45. Refresh button do not work, main windows is blank after startup.

**Comment by fleamour** [comment]
Same under Tumbleweed KDE.

**Comment by ferBV** [comment]
I have the same problem in EndeavourOS with kde, both with the flatpak and the AUR.

**Comment by jubalh** [comment]
I doubt these  "I have this also with this desktop in this distribution" comments will help.
We need version numbers, need to see what changed etc etc.

BTW I also run NVIDIA and recently I disabled that driver and used the Intel card. And then whats-app-for-linux loaded. Now back to NVIDIA and it doesn't. I'm not sure this was the only system change (I doubt it).
But can anyone confirm? Do all the people with this issue run NVIDIA?

**Comment by Pryka** [comment]
Yes I'm on Nvidia and my distro is Debian Stable. I use whats-app-for-linux from Flatpak.

**Comment by fleamour** [comment]
Turning hardware acceleration to off solves for me.

**Comment by anishjp** [comment]
> Turning hardware acceleration to off solves for me.

Where do you see this setting?

**Comment by Pryka** [comment]
> Turning hardware acceleration to off solves for me.

Not a solution for me I mean it does works but it reintroduce bug with mashing refresh buton https://github.com/eneshecan/whatsapp-for-linux/issues/330

**Comment by jubalh** [comment]
For others with this problem:
I switched to https://github.com/keshavbhatt/whatsie which works fine.
