### ISSUE TITLE
Crash on file download.

### ISSUE THREAD

**Issue by juxuanu** [eneshecan/whatsapp-for-linux#38]
The app crashes with **segmentation fault** when trying to download a file. Either from personal chat or group chat.
I'm using Gnome 3.36.4 in ArchLinux_x86-64 with kernel `5.4.51-1-lts`. The `whatsapp-for-linux` version is `1.0.7-1`.

Any more logs that you need, just ask.

**Comment by eneshecan** [comment]
Thanks for reporting this! I was thinking this might be related to snap interfaces but I guess aur package is not based on snap. Needs to be tested/debugged on Arch Linux since I haven't experinced this so far.

**Comment by juxuanu** [comment]
Ok, I've noticed that the segfault is Gnome's fault. It happens when you have your Google Drive mounted in Nautilus. I'll report it there.
You can close this :-)
