### ISSUE TITLE
Dark mode not needed anymore.

### ISSUE THREAD

**Issue by juxuanu** [eneshecan/whatsapp-for-linux#39]
Whatsapp [implemented an option](https://imgur.com/SOqLYwA) in their web app that allows you to switch to dark mode. The `whatsapp-for-linux` dark mode is not needed anymore.

**Comment by eneshecan** [comment]
Wow, good news! We need to remove that option now :)

**Comment by juxuanu** [comment]
https://github.com/eneshecan/whatsapp-for-linux/pull/40
