### ISSUE TITLE
snap installed whatsdesk shows boxes and not characters on "download" screen

### ISSUE THREAD

**Issue by skinorth439** [eneshecan/whatsapp-for-linux#409]
Ubuntu 24.04.10 LTS "noble" running Whatsdesk R 0.3.8 shows boxes instead of decipherable fonts/characters on "Download" screen.  Whatsdesk was running without problems before I attempted the 24.4 upgrade on this machine.  The upgrade failed and I recovered it without really understanding what failed.  Indications I get from Googling the Whatsdesk problem are that it's some kind of a font-related issue.

I have tried re-installing Whatsdesk on this machine and on another one running the same version of Ubuntu with identical results.  This second machine is a fresh Ubuntu 24.04 install from USB stick and the standard download which I did about a month ago.

I apologize for my lack of Linux/Ubuntu sophistication.  Please let me know what other info would help here

I have a third machine running Ubuntu 24.04.5 LTS "Jammy", and I installed Whatsdesk 0.3.8 on it just today and it seems to work properly.  The problem which occurs on the other two machines does not occur on the Downoad page on the third machine.  The screenshot shows what I get when I attempt to Download an image.

![Screenshot from 2024-09-15 13-26-43](https://github.com/user-attachments/assets/186ebe48-96b0-4951-828a-0bfb20649c47)

**Comment by eneshecan** [comment]
Hi, whatsdesk is not whatsapp-for-linux

**Comment by skinorth439** [comment]
My apologies for posting this matter where I guess it was not appropriate.  My mistake.
________________________________

**Comment by eneshecan** [comment]
No worries :)
