### ISSUE TITLE
Hide menubar

### ISSUE THREAD

**Issue by ltadeu6** [eneshecan/whatsapp-for-linux#41]
I find it kind of annoying after a wile, could you implement an option to hide it under the view menu???

**Comment by eneshecan** [comment]
Hi, thanks for the support! Do you mean the menubar?

**Comment by ltadeu6** [comment]
yes, I think so, I'm talking about this: 
![image](https://user-images.githubusercontent.com/52164335/88719702-158a2d80-d0fa-11ea-8d72-4ab2b0b55413.png)

**Comment by eneshecan** [comment]
Alright then, let's see if we can do that!

**Comment by juxuanu** [comment]
What about, since we are using Gtk, to add an overflow menu to have all those options inside the title bar? I think it could look nice and more integrated with the Gtk idea.

**Comment by eneshecan** [comment]
#46 fixed this.
