### ISSUE TITLE
error output at beginning

### ISSUE THREAD

**Issue by muralikodali** [eneshecan/whatsapp-for-linux#44]
on Arch linux it is giving following error while starting , though application is working without problem.

following  is the error output :  

```
** (whatsapp-for-linux:63599): WARNING **: 15:25:49.272: Error loading plugin: /usr/lib/enchant-2/enchant_nuspell.so: undefined symbol: _ZN7nuspell2v36Finder25search_all_dirs_for_dictsEv

Settings: Key file does not have key “allow_permissions” in group “Network”
```

**Comment by eneshecan** [comment]
Hi @muralikodali, thank you for this. Yes, I am aware of this and planning to make an aur package with those dependencies included. See #42 please.
