### ISSUE TITLE
No Voice and Camera Capture

### ISSUE THREAD

**Issue by kawaK1320** [eneshecan/whatsapp-for-linux#47]
ive seen the notification on this issue the first time i run the app... i love it BTW.

Im using arch kde plasma
 will this issue be fixed?
i could find this one, cant paste image, and it reports as macos
thanks!

**Comment by kawaK1320** [comment]
also links in tabs and AUR opens libre office! its the only app that does this, i dont think it is my system!

**Comment by eneshecan** [comment]
Hi, thanks for the support! Could you please elaborate on what is the exact problem? Can't you play voice notes or record?

**Comment by kawaK1320** [comment]
hi, sorry for the delay!  i cant record!

**Comment by eneshecan** [comment]
Hello, thanks for the issue. I also just noticed this, can confirm. Needs to be investigated.

**Comment by kawaK1320** [comment]
hey! i just noticed that when listening any audio, the progress bar does not follows properly, also it wont autoplay adyacent voicenotes / audios!

**Comment by eneshecan** [comment]
Thanks a bunch! We have some media capture and play problems. I will investigate those soon...

**Comment by Ticiano-mw** [comment]
I am not able to play audios at all. Using Ubuntu 20.04 and the latest stable snap (1.0.9)
Got a warning the first time I opened the app, saying that in order to have camera and audio I needed to use one of the supported browsers (Opera ,Chrome or Firefox)
@eneshecan

**Comment by Ticiano-mw** [comment]
![image](https://user-images.githubusercontent.com/62998927/95363943-88f0ae00-08a6-11eb-9349-7eca0a16d984.png)
On my phone, the session appears as MacOS/Safari so I guess that's why.

**Comment by Ticiano-mw** [comment]
I tried changing language to English on my phone (WhatsApp app) but the issue persists:
![image](https://user-images.githubusercontent.com/62998927/95364282-061c2300-08a7-11eb-9c32-99dc33947146.png)

Cannot play audios at all

**Comment by eneshecan** [comment]
Not being able to play audio may be related to snap interfaces but last time I checked it was working. Could someone else confirm this?

**Comment by eneshecan** [comment]
Well, it seems that Whatsapp doesn't allow/support WebKit framework to capture any audio or video... This can be also observed on Epiphany Browser which is WebKit based.

**Comment by Ticiano-mw** [comment]
Damn... thanks for looking into it @eneshecan 
So I suppose they changed the behavior, since it was working for you previously?

**Comment by eneshecan** [comment]
No, playing audio/video is supposed to work but no recording...

**Comment by Tuxino88** [comment]
whatsapp will soon allow you to make calls and video calls from "whatsapp-web", perhaps it would be more profitable to switch to a different rendering engine such as nidium , I doubt whatsapp will consider webkit in the future.

https://www.nidium.com/
