### ISSUE TITLE
Option to use native window frame

### ISSUE THREAD

**Issue by Babbie** [eneshecan/whatsapp-for-linux#52]
I prefer my windows to have no title bar, and the default GTK one doesn't match the rest of my windows. If possible, I'd like a setting to toggle the window decorations to the desktop default. For accessing the options, perhaps pressing alt would work?

**Comment by eneshecan** [comment]
Hello, thanks for the feedback. Well, we followed the headerbar mechanism of Gnome but we might make this configurable somehow.

**Comment by eneshecan** [comment]
Done.
