### ISSUE TITLE
Title header, reload icon missing

### ISSUE THREAD

**Issue by keshavbhatt** [eneshecan/whatsapp-for-linux#56]
The reload button in the header is missing the reload icon, and shortcuts in the right-hand side menu are not working.
![header bug](https://user-images.githubusercontent.com/5965031/97812374-e1994800-1ca6-11eb-9f1b-6bbdefa9d69b.png)

Version info:
whatsapp-for-linux  -  1.0.9 
Ubuntu 16.04 Unity Desktop 
Installed using snap

Thanks for the nice application :)

**Comment by eneshecan** [comment]
Hello @keshavbhatt. Thank you for the feedback!. You may have a missing decent icon theme in your setup or this is a problem with Ubuntu 16.04.

**Comment by eneshecan** [comment]
I would suggest you to upgrade your distro to 20.04 if there is nothing against it.

**Comment by keshavbhatt** [comment]
Is there any mechanism in gtk+ where you can set the fallback icons if the chosen theme does not provide the icon for some reason?

**Comment by eneshecan** [comment]
I am not sure but doing that in the code is not feasible.
