### ISSUE TITLE
Can't play/download video files with snap

### ISSUE THREAD

**Issue by emmegamma** [eneshecan/whatsapp-for-linux#58]
I tried opening some videos sent by a friend (mp4 format). By default, the app tries to play them, but it fails ("impossible to play the video", though I think I also got a message "file type not supported" at some point), and it doesn't give any download option.

Unfortunately I got this as the first impression when opening the app, but it does look great!

**Comment by eneshecan** [comment]
Could you please tell me which package are you using and your distro?

**Comment by emmegamma** [comment]
I'm on Ubuntu 20.04
The issue is only with the snap app. I installed the deb package today, and videos play fine there.

**Comment by eneshecan** [comment]
Fixed with 0a43f9467617cc72e8ba86abe513f2adc169a07f
