### ISSUE TITLE
Keyboard shortcut to navigate around faster.

### ISSUE THREAD

**Issue by MasterMynk** [eneshecan/whatsapp-for-linux#60]
Your version of Whatsapp is just awesome. It would be nice if you could add a keyboard shortcut which would open a menu which will help you to search through all the chats available. Yeah I know that there is a search option available but a keyboard shortcut to open that would be nice so that I don't have to use my mouse to click on the search bar.

I would like something like what discord has. Where you press Ctrl + K (or even Ctrl + F) and the menu opens, then you just type the name and then press enter to open the chat. This would make the it more keyboard-centric and hence more faster to use.

**Comment by eneshecan** [comment]
Well, unfortunately, whatsapp web doesn't provide the API to make it possible to do this.

**Comment by MasterMynk** [comment]
Is there a way to shift the mouse focus from the "Type a message" text box to the "Search or start a new chat" text box after pressing a key or a combination of keys?

**Comment by eneshecan** [comment]
Well, afaik you can navigate through controls on the screen in order, you can use `tab` and `shift+tab`.

**Comment by MasterMynk** [comment]
Oh yeah it does work! Thanks for letting me know. Anyways this is off-topic but please accept the system tray pull request if it works, because even I would like to have that feature. Also should I close this issue?

**Comment by eneshecan** [comment]
Hi @MasterMynk, glad that you found out! We are working on the system tray but we have a couple of problems that need some help. And yeah, you can close the issue.

**Comment by MasterMynk** [comment]
@eneshecan 👍
