### ISSUE TITLE
title bar behavior to alt+tab

### ISSUE THREAD

**Issue by gauraputu** [eneshecan/whatsapp-for-linux#61]
I'm not sure whether this is intended but whenever I alt+tab the title bar would hide/show. it throw me off because at times the title bar would be there, then when I alt+tab again it would gone. I see in #52 this feature is intended to hide/show title bar but not sure if it's intended to hide/show it when alt+tabbing.

**Comment by eneshecan** [comment]
Hi, thank you for reporting this. This is definitely a bug and needs to be fixed.

**Comment by eneshecan** [comment]
Fixed with #98ae480.

**Comment by eneshecan** [comment]
Hİ @agichim. We recently changed shortcut to Alt+H. Manjaro must be using an old version in this case.

**Comment by agichim** [comment]
> Hİ @agichim. We recently changed shortcut to Alt+H. Manjaro must be using an old version in this case.

It worked! Thank you. I didn't look for any docs if there are any to check for keyboard shortcuts.
