### ISSUE TITLE
Title bar doesn't show up anymore

### ISSUE THREAD

**Issue by lastbreak** [eneshecan/whatsapp-for-linux#66]
Hello guys,

I've been using Whatsapp for linux for sometime now and thanks for the recent tray icon feature update.
But since the last updats the title bar disappeared and now I can't move the window, minimize, maximize or close directly from the window program.
I'me using Manjaro GNOME 20.2 and I don't have any more similar issues with other applications.

**Comment by eneshecan** [comment]
Hi, it's kind of a hidden feature, so you can reenable it by pressing ALTm

**Comment by lastbreak** [comment]
Sorry, didn't know about that...maybe I should search a little longer about this features.
Thanks and keep the good work on the best whastapp app for desktop on linux.

**Comment by eneshecan** [comment]
No problem, thanks a lot for the great feedback :)
