### ISSUE TITLE
Can't save files into other that Downloads folder

### ISSUE THREAD

**Issue by rbnmndz** [eneshecan/whatsapp-for-linux#70]
Hi,
When I'm trying to save a file (image or document), the folder selector window is opened but without the name file selector row. I choose the folder and nothing is saved.

[Here an image](https://imgur.com/a/Ckx1Vib) of saving a file with your app compared to saving it with Thunderbird.

I'm working with kde neon 5.20, but with all the gtk's libraries needed. I've installed whatsapp-for-linux_1.1.0_amd64.deb and also the snap package (both the same behaviour)

Thanks.

**Comment by eneshecan** [comment]
Hi @rbnmndz, thanks for the feedback. However, since the application is run by the user, it cannot write to any system folders. Could you please try to write into a folder in your home?

**Comment by rbnmndz** [comment]
I've just realized what it seems the problem is: the select folder window doesn't work. It always saves on ~/Downloads. No matter which folder has been selected. It would be better if we could also set the file name.

And now I see which is the filename it is assigned "WhatsApp Image date_time_posted.jpeg" for images and the original name for documents. BTW, /tmp is writable for everyone. I use it a lot for downloading files that I don't want to save permanently. 
@eneshecan, thanks for your app and attention.

**Comment by eneshecan** [comment]
Oh, didn't know `/tmp` is writable for everyone. Thanks for pointing that out. I will check this issue soon.

**Comment by eneshecan** [comment]
Fixed by #d5ae589
