### ISSUE TITLE
Whatsapp web client shows up as Mac

### ISSUE THREAD

**Issue by frederico-klein** [eneshecan/whatsapp-for-linux#77]
**Description**
Whatsapp web client shows up as Mac OS on the "logged in devices tab". This is quite minor. Also I really like the project. Kudos. 

**To Reproduce**
1. Log in.
2. See wrong info. 

**Expected behavior**
Show up as Linux.

**Screenshots**

**Environment**
 - Ubuntu 18.04
 - snap

Hopefully it is as simple as changing a text somewhere.

**Comment by eneshecan** [comment]
Hi, thanks for the details. Please see #23.

**Comment by frederico-klein** [comment]
I figured it out after reading this: https://trac.webkit.org/wiki/WebKit2
It's maybe a bug with whatsapp, or an improvement? No idea. Maybe just close it.
Cheers!
