### ISSUE TITLE
Reopen from system tray sends the window program to the back

### ISSUE THREAD

**Issue by lastbreak** [eneshecan/whatsapp-for-linux#78]
**Description**
When I reopen the app from the system tray it should appear on top of all the windows that I have open but it sends it always to the back of all the windows that I have open. For example, if I'm on my browser doing something and suddenly I need to open Whatsapp for linux to reply a message it always open in the back of the browser window that I was working on.
And other issue, is that the app does not remember it's position on the screen everytime I reopen it.

**To Reproduce**
1. Go to 'Whatspp for linux app icon on the system tray'
2. Click on 'Open'
3. See the bug that it always send it to back of all the windows that you've open.

**Environment**
 - Distro: Manjaro GNOME - Linux kernel 5.10.2-2-MANJARO x86_64 20.2 Nibia
 - Package [from AUR]

**Comment by eneshecan** [comment]
Hello, I think this is platform-specific. On Gnome, I see a notification that says Whatsapp for Linux is ready and the app is in the background. Is this the case for you?

**Comment by lastbreak** [comment]
Yes @eneshecan that's what is happening.

**Comment by eneshecan** [comment]
Well, in this case, this is a behavior of Gnome. I am sorry that we can't do more. Try other tray icon gnome extensions like this one https://extensions.gnome.org/extension/1031/topicons/

**Comment by lastbreak** [comment]
Ok, understood. Maybe on the upcoming GNOME 40 version this could be solved...I will try it when it comes available.
