### ISSUE TITLE
Raise application window when clicked on notification

### ISSUE THREAD

**Issue by MauricioGlz** [eneshecan/whatsapp-for-linux#80]
**Description**
When a new message comes and the notification appears, after clicking nothing happens.

**To Reproduce**
1. Get a new message.
2. Click the notification.

**Expected behavior**
After clicking the application should open that message or at least the app.

**Environment**
 - Ubuntu 20.04.1
 - Deb package

**Comment by eneshecan** [comment]
Hello @MauricioGlz. Thanks for the request. Needs to be looked into GTK about notifications to make it possible. Any help is appreciated.

**Comment by adehghanzadeh** [comment]
Hi there
Lots of thanks for this project
====
After upgrading to 1.4.1, this issue still remained (clicking on tray icon result in showing a popup menu (Show , About, and Quit))
Dist: Debian (testing branch)
DE: Gnome 41.2

**Comment by eneshecan** [comment]
Hi @adehghanzadeh. This issue is about clicking on notifications. If I understand your comment right, you want the application window to be raised on clicking on the tray icon but this was not possible with libappindicator and now we switched to libayatana-appindicator it might be possible but I doubt it.

**Comment by adehghanzadeh** [comment]
Hi @eneshecan 
Oh my god, yes, I meant that.
If its possible, it would be great...

**Comment by Vistaus** [comment]
It doesn't work on KDE Plasma either. If I click the notification while the window is minimized, the window doesn't get raised. It does work for other applications (KDE/Qt ones), however.
