### ISSUE TITLE
Quick response with notification.

### ISSUE THREAD

**Issue by MauricioGlz** [eneshecan/whatsapp-for-linux#81]
**Is your feature request related to a problem? Please describe.**
When having a chat it's more practical to just quickly respond a new message from the notification than having to open the window app and response there.

**Describe the solution you'd like**
A simple single line text area with a "send" button will be great if possible.

**Comment by eneshecan** [comment]
Well, since we can't access whatsapp's API, this would be very tricky and hacky to implement, hence not possible at the moment.
