### ISSUE TITLE
Option to start in tray

### ISSUE THREAD

**Issue by Shabinder** [eneshecan/whatsapp-for-linux#83]
Keep app in the tray on startup if start in tray is enabled.

**Comment by berkeyvx** [comment]
I can work on this. Let me know if you did not start @eneshecan

**Comment by eneshecan** [comment]
Okay then, let's separate this into two;

- @berkeyvx The thing you did is related to `start as closed to tray`, so you only need to check if closed to tray option is enabled in the settings and if so, hide the window on startup.
- Secondly, we can implement auto start with system which is not related to system tray at all.

**Comment by eneshecan** [comment]
@Shabinder Let me know your thoughts about this, please.

**Comment by eneshecan** [comment]
On second thought, hiding the window on startup if closed to tray is active might not be desired for most of the users.

**Comment by berkeyvx** [comment]
> On second thought, hiding the window on startup if closed to tray is active might not be desired for most of the users.

I agree with that. That is why i put another key and switch. Maybe we should make another menu for these kind of options.

**Comment by eneshecan** [comment]
@berkeyvx Honestly, I wouldn't put an option for such a small thing that is not desired by most of the users. For me, I would like to see the window when I start the application regardless of the state of the tray icon, and most of the chatting applications are designed that way. I would say let's cancel this feature but hearing out more opinions from other people would be nice!

**Comment by berkeyvx** [comment]
>  I would like to see the window when I start the application regardless of the state of the tray icon
Same
>  I would say let's cancel this feature 
We can keep some parts of pull request for issue #86 .(Like new key for start on closed to tray). Autostart on system startup closed to tray is good feature in my opinion. We can use some of parts for this.

**Comment by Shabinder** [comment]
> We can keep some parts of pull request for issue #86 .(Like new key for start on closed to tray). Autostart on system startup closed to tray is **good feature** in my opinion.

 It is good , even for instance telegram app has it , some users like me , just need to be connected to whatsapp , we dont need to see the main window on startup , notifications do suffice for alerting us.

**Comment by Shabinder** [comment]
> We can keep some parts of pull request for issue #86 .(Like new key for start on closed to tray). Autostart on system startup closed to tray is **good feature** in my opinion.

 It is good , for instance telegram app also has this feature , some users like me , just need to be connected to whatsapp , we dont need to see the main window on startup , notifications do suffice for alerting us.

**Comment by eneshecan** [comment]
I see, then I will review the pr soon. However, beware that autostart feature has no relation with this, the application will start itself according to the settings i.e. as hidden if the related option is enabled.

**Comment by bayazidbh** [comment]
So, I've made sure the Start From Tray is on, but it doesn't seem that the setting is retained after each run? Same with Close To Tray setting - it works, but if I quit the app and then re-run it, all settings are back to default. I'm using the Snap version of Fedora 33 if that matters? The AUR version I run on my Manjaro PC doesn't have that issue.

**Comment by eneshecan** [comment]
@bayazidbh Thanks! Please make sure that you are running the latest version. If you did so, could you please create an issue with detailed information?
