### ISSUE TITLE
Double click tray icon to show app

### ISSUE THREAD

**Issue by dt192** [eneshecan/whatsapp-for-linux#87]
It would be great if I could double click the tray icon to show the app.

The ckb-next app has this behaviour (single click opens the menu, double click shows the app), so it's definitely possible.

**Comment by eneshecan** [comment]
Hi, I don't think that's possible with the appindicator library since it doesn't provide any click handlers for the icon. However, maybe a workaround could be found...

**Comment by eneshecan** [comment]
Hi again @dt192. I investigated a bit more and found out that this is not possible with the libappindicator. So, I am closing this issue.

**Comment by dt192** [comment]
Ok, many thanks for checking.
