### ISSUE TITLE
Control + Q to quit the app including the system tray icon

### ISSUE THREAD

**Issue by raphtlw** [eneshecan/whatsapp-for-linux#88]
Could you add a keyboard shortcut that quits the app when ctrl q is pressed? It would be very convenient to have.

Thanks!

**Comment by eneshecan** [comment]
Sure, there is already a quit button, we can assign the shortcut to it and close the app immediately when pressed/triggered.

**Comment by eneshecan** [comment]
Implemented with 050abc6ddecb4f3e40220f10276ec02d6821ba81
