### ISSUE TITLE
Fullscreen mode showing black borders

### ISSUE THREAD

**Issue by TimestaticYT** [eneshecan/whatsapp-for-linux#89]
**Is your feature request related to a problem? Please describe.**
When I go into fullscreen mode or maximize the window i get ugly black borders.

**Describe the solution you'd like**
I would be great if it would scale better. I don't know if this is possible but the borders are just really annoying. Maybe even a quickchat window in the system tray would be very handy.

**Comment by eneshecan** [comment]
Hi @TimestaticYT. Thanks for reporting. Do you mean the black bars on left and right?

**Comment by TimestaticYT** [comment]
Yes! This really bothers me! I don’t know if it’s possible but I would love to see that enhancement. I mean what’s the point of fullscreen mode if it’s just gonna fill in black bars

**Comment by eneshecan** [comment]
> Yes! This really bothers me! I don’t know if it’s possible but I would love to see that enhancement. I mean what’s the point of fullscreen mode if it’s just gonna fill in black bars

Well, this is the same with whatsapp web. You could try setting zoom level to higher value like 120%

**Comment by eneshecan** [comment]
Closing this issue since there is nothing to do on our side.
