### ISSUE TITLE
Implement system tray icon

### ISSUE THREAD

**Issue by eneshecan** [eneshecan/whatsapp-for-linux#9]

**Comment by eneshecan** [comment]
Unfortunately, Gtk::StatusIcon is deprecated and couldn't find a way to get it working on Gnome. Will have to investigate other libraries/solutions for this.

**Comment by eneshecan** [comment]
However, `libappindicator` api can be used

**Comment by dobroweb** [comment]
Please see my PR https://github.com/eneshecan/whatsapp-for-linux/pull/49
