### ISSUE TITLE
Workaround for audio messages

### ISSUE THREAD

**Issue by Tuxino88** [eneshecan/whatsapp-for-linux#91]
Since whatsapp insists on not wanting to support webkit and the web version in general, leaving us out even with calls and video calls, my idea was this:
For audio messages it would be convenient to introduce an "external" recorder that automatically records and sends audio files such as an mp3 file for example, it's not the best but better than nothing right?

**Comment by Tedium16** [comment]
That could actually work, make the program access I lightweight recorder that it would set as a dependency and run in the background, record the audio then automatically attach it as a mp3 that can be sent

**Comment by eneshecan** [comment]
Definitely a good idea. Thanks @Tuxino88! I will come up with some research and UI design to achieve this.

**Comment by Tuxino88** [comment]
> Definitely a good idea. Thanks @Tuxino88! I will come up with some research and UI design to achieve this.

Thanks to you :D

**Comment by eneshecan** [comment]
I am closing this since the audio recording works now.
