### ISSUE TITLE
Spell check not working

### ISSUE THREAD

**Issue by Tedium16** [eneshecan/whatsapp-for-linux#92]
The spell check isn't working on the latest version 1.1.5
I am running arch linux, on the 5.11.2 kernel and I installed the AUR pkg with paru aur helper.

**Comment by eneshecan** [comment]
Hi @Tedium16. I can confirm. Needs to be looked into.

**Comment by Tedium16** [comment]
Glad I could be of help

**Comment by eneshecan** [comment]
It seems that currently, webkit requires us to install the corresponding dictionary with our system language. For example if your system language is English, you should install `aspell-en` package to get it working. I will either try to automatize this in the installation or add some instructions in README to inform users.

**Comment by Tedium16** [comment]
I installed the package and, it worked fixed the issue.

**Comment by eneshecan** [comment]
@Tedium16 Great! I will add the instructions to README soon.

**Comment by eneshecan** [comment]
Fixed with 8236c0bdba98e3353f78acf13c223913904c3e63
